juttle/juttle

- lib/adapters/http/read.js
- lib/adapters/http/write.js
- lib/adapters/parsers/index.js
- package.json
- test/adapters/http.spec.js
fixes #1 by just ripping out request-promise for now and using the
request library directly so we don't end up mixing stream events and
promise chains and having timing issues.
> fix issue #1 read http not failing on bad status code

- lib/sinks/client-sink-mgr.js
- lib/strings/juttle-error-strings-en-US.json
- test/cli/cli.spec.js
Use a specific error RT-INVALID-VIEW when a program refers to a view
that isn't supported by the runtime (i.e., for the cli, by the client
sink manager).
@demmer
> Use more specific error for unknown views.

- README.md
This adds a gitter badge to the readme.
It is essentially the same change as #9 except it puts the badges on the same line instead of one after another, and keeps the Travis badge first.
> README: add gitter badge

- lib/cli/errors.js
- test/cli/cli.spec.js
For error strings like:
<input>:1:17:
1:read from gmail -from :1 hour ago: | view table
^^^^^
Options must be specified before filter expressions. code (JUTTLE-SYNTAX-ERROR-WITHOUT-EXPECTED)
the "code " is not needed, so remove it.
@dave @mnibecker
> Drop the "code " from the error string.

- test/adapters/parsers/csv.spec.js
- test/adapters/parsers/json.spec.js
- test/adapters/parsers/jsonl.spec.js
Update the various parser tests to return a promise from each test
case and include the checks as part of the promise chain as opposed
to the previous approach in which the tests would throw expectation
errors from within the context of the emit callback.
This should help localize failures more clearly.
As part of this change, update the tests to properly handle the case
where the parser is given a limit on the number of points per emit
so that it properly expects an empty array at the end of the test.
This was causing intermittent failures in travis as identified in #13.
> test: rework the unit tests for the parsers to be more robust

- lib/parser/juttle-parser.js
A couple of structural changes in the `parser` module which make `parse` and `parseSync` more readable, more DRY, and closer together structurally. Eventually, they should be identical except for the sync/async difference.
> Parser cleanups: Structural changes

- README.md
- docs/adapters/index.md
- docs/reference/cli.md
- mkdocs.yml
Add to mkdocs.yml, add link to adapters page from adapters section,
add link for gmail adapter on adapters page.
@dmehra can you double-check that I added the link to mkdocs.yml properly?
> Address feedback on cli docs.

- lib/sinks/client-sink-mgr.js
- lib/sinks/table.js
- lib/sinks/text.js
- test/cli/cli.spec.js
Currently the following juttle program:
```
emit -from :2015-01-01: -limit 2
| (put sink=1 | view table;
put sink=2 | view table)
```
Would result in the following output:
```
┌────────────────────────────────────┬──────────┐
│ time                               │ sink     │
├────────────────────────────────────┼──────────┤
│ 2015-01-01T00:00:00.000Z           │ 1        │
┌────────────────────────────────────┬──────────┐
│ time                               │ sink     │
├────────────────────────────────────┼──────────┤
│ 2015-01-01T00:00:00.000Z           │ 2        │
├────────────────────────────────────┼──────────┤
│ 2015-01-01T00:00:01.000Z           │ 1        │
├────────────────────────────────────┼──────────┤
│ 2015-01-01T00:00:01.000Z           │ 2        │ …
```
> don't interleave output from multiple client views

- lib/runtime/adapters.js
Downgrade the adapter init logging message from info to debug and
include some timing info to see how long it takes for the adapter to
load and to be initialized.
> adapters: downgrade initialization logging and add timing info

- docs/concepts/programming_constructs.md
- docs/examples/concepts/import_module_from_url.juttle
There was a misconception that URL import wasn't implemented on the CLI and so the example was removed; the actual problem was with obsolete syntax of the gist that exports the module. I fixed the gist in jut-test account, now import works fine. 
I had to leave the import examples (both inlined in the docs, and the examples file) not covered by the syntax check, as our `gulp examples-check` task is unable to parse the module dependency:
```
Error: checking /Users/dmehra/git/juttle/docs/examples/concepts/import_module_from_url.juttle: CompileError: Error: could not find module "https://gist.githubusercontent.com/jut-test/273396ac4efcc838687b/raw/dde7c96c7560c38a29881d0345fc2d5727ee082e/main.juttle"
at /Users/dmehra/git/juttle/gulpfile.js:226:26
at tryCatcher …
```
> Adding back example of import via URL

- gulpfile.js
with these settings we'll have better settings for running tests in
general in travis
fixes #18 by simply tweaking the timeouts to better match the expectations of running tests in travis
> increase the test timeout and also tweak the slow value

- lib/adapters/file-adapter.js
- test/adapters/file/file.spec.js
fixes #65
this includes the ability to specify the -from/-to options to `read
file` as well as the ability to detect out of order points and drop
them with a warning.
> add -from/-to to `read file`

- bin/juttle
The normal processing of any errors in the juttle just prints the
error message but doesn't include the full stack trace. This is
appropriate for problems in the user programs, but makes it a pain
to track down errors when working on the compiler core.
To help this, add a debug log for any errors that come out of the execution or
compiler that includes the full stack trace.
> cli: add debug logging to show juttle errors with stack traces

- docs/adapters/file.md
- lib/adapters/file/index.js
- lib/adapters/file/read.js
- lib/adapters/file/write.js
- lib/adapters/index.js
- lib/adapters/parsers/csv.js
- lib/adapters/parsers/json.js
- lib/adapters/parsers/jsonl.js
- lib/strings/juttle-error-strings-en-US.json
- test/adapters/file/file.spec.js
- test/runtime/specs/juttle-test-utils.js
this PR reworks the file adapter so its easier to add more features in
the future by splitting the read and write up into individual modules.
the fix for issue #6 is currently to set a write limit so that we
simply limit writing out no more than 100K JSON points in the currently
supported writing format of JSON.
future work could be to include streamable writing formats such as CSV,
or JSONL (jsonlines: http://jsonlines.org/)
> Fix file adapter to handle large files

- lib/runtime/procs/stoke/cdn.js
A naive invocation of `read stochastic -source 'cdn' -last :1w:` would
trigger the limit of 1000 syslog messages.
Bump up the limit to 100000 to make this less likely to occur.
Fixes #39.
> stochastic: bump up the syslog max limit

- docs/adapters/file.md
- lib/adapters/file/write.js
- test/adapters/file/file.spec.js
fixes #100
In my hastiness to get pr #11 in I changed the wrong option to be
bufferLimit resulting in a messy set of options which should be cleared
up now with this PR.
> rename options for write to match desired naming scheme

- lib/strings/juttle-error-strings-en-US.json
Add a new error RT-MISSING-TIMERANGE-ERROR to handle the case where no
-from, -to, or -last is specified. This reflects the first example in
https://github.com/juttle/juttle/wiki/Time-Range-Semantics.
@dmajda @demmer @go-oleg
> Add error for no -from/-to/-last.

- CONTRIBUTING.md
resolves #99
I used [puppet](https://github.com/puppetlabs/puppet/blob/master/CONTRIBUTING.md) and [atom](https://github.com/atom/atom/blob/master/CONTRIBUTING.md) docs as examples. The filename [CONTRIBUTING.md](https://github.com/blog/1184-contributing-guidelines) is standard.
We are missing something like a [CLA](https://en.wikipedia.org/wiki/Contributor_License_Agreement) or Certificate of origin like [nodejs](https://nodejs.org/en/get-involved/development/#developers-certificate-of-origin-10). It's not clear to me how critical is to have one, and must it be explicitly signed (using a tool like [clahub](https://www.clahub.com/) perhaps?) or is it enough to mention that by contributing, you allow to abide by the CLA.
@mccanne @demmer @dmajda
> Adding contributing guidelines

- lib/views/table.js
- test/views/table.spec.js
In progressive mode, look at all the points in the first call to
consume when determining the set of columns and widths instead of
only looking at the first point.
Fixes #33.
> table: look at all points in the batch to determine column widths

- docs/concepts/programming_constructs.md
- docs/processors/join.md
- docs/processors/reduce.md
> Documentation fixes

- bin/juttle
- lib/views/file.js
- lib/views/table.js
- lib/views/text.js
- lib/views/view.js
- test/views/table.spec.js
Previously if a warning was emitted by a view, the message would be
output as something like:
undefined 'Sink undefined: Ignoring new point key(s) "key2"'
Fix the two `undefined` above by tiding the way the CLI prints out
warning events and by adding a static name property to each view
instead of expecting it to be passed into the options in the constructor.
Partially addresses #41
> cli: fix 'undefined' in view warning output

- lib/adapters/stochastic-adapter.js
- test/adapters/stochastic.spec.js
Since :beginning: is actually an infinite moment, stepping forward ended up
causing an infinite loop.
Add a fix for this by explicitly checking for `-from :beginning:` and
implicitly converting it to start at the epoch instead.
Partially addresses #31.
> stochastic adapter: fix infinite loop when run with -from :beginning:

- lib/adapters/file/read.js
- lib/adapters/http/read.js
- lib/adapters/stochastic-adapter.js
- lib/program.js
- lib/runtime/procs/emit.js
- lib/runtime/procs/procs.js
- test/runtime/test-adapter.js
Remove `sourceType` property on procs and instead rely on `Juttle.proc.source` being in the inheritance chain.
Refs: https://github.com/juttle/juttle/issues/54
Corresponding PRs for adapters will reference this one.
> Drop sourcetype

- lib/compiler/ast-visitor.js
- lib/compiler/autocompleter.js
- lib/compiler/build.js
- lib/compiler/flowgraph/implicit_views.js
- lib/compiler/flowgraph/program_stats.js
- lib/compiler/flowgraph/views_sourceinfo.js
- lib/compiler/graph-builder.js
- lib/compiler/graph-compiler.js
- lib/compiler/semantic.js
- lib/parser/parser.pegjs
- lib/program.js
- lib/runtime/procs/procs.js
- test/compiler/autocompleter.spec.js
- test/compiler/program_stats.spec.js
- test/runtime/adapter.spec.js
- test/runtime/deactivate.spec.js
- test/runtime/graph-api.spec.js
- test/runtime/specs/juttle-test-utils.js
Another pass through the compiler to replace instances of 'sink' with 'view' as appropriate.
Details in the specific commits.
Closes #24 
Note that outrigger will need to be updated once this merges.
> finish renaming sink to view

- lib/parser/parser.pegjs
There are no sink names as a separate concept in the grammar anymore.
Discovered during review of #115.
> Grammar: Fix outdated comment

- lib/compiler/build.js
The result was unused. Everything important is collected in `GraphBuilder`.
Discovered during review of #115.
> Build: Do not return anything from generated build function

- lib/compiler/filters/filter-checker.js
- lib/compiler/graph-compiler.js
- lib/compiler/semantic.js
- test/runtime/specs/juttle-spec/filter-expressions/expression-filter-terms.spec.md
Allow using equality operators (`=`, `==`, `!=`), comparison operators (`<`, `>`, `<=`, `>=`), and `in` to compare fields with other fields in `filter`.
Resolves #120.
> Implement field-to-field comparisons in `filter`

- bin/juttle
To fix #81, include 2 changes that both address the problem in different
ways. I think I'll keep both fixes just to allow for flexibility in
case we want to change the behavior later.
The first fix involves collapsing multi-line programs to a single line
when saving to history. That way, scrolling through history doesn't
result in an ugly multi-line item, and also allows for editing of the
item. When the multi-line program is run for the first time, however,
it's still run as a multi-line program. That allows any errors to be
shown in the context of the original multi-line program.
The second fix is to allow multiline inputs to work with history. The
problem was that the '.*' regex wasn't matching multiple lines
separated by newlines. Javascript regex apparently doesn't have a
multi-line …
> Fix multiline inputs and history.

- lib/parser/parser.pegjs
- test/runtime/specs/juttle-spec/filter-expressions/simple-filter-terms.spec.md
The removed hack was intended to improve error messages in programs where the author used an option after a filter expression in `read`, which is illegal:
read file level = 'error' -file '~/my-data.json'
In these cases, the `-file` part was originally mistakenly considered a full-text term, parsed as such, and the compiler later produced an error like this:
Error: file is not defined
The hack improved such messages. However, it also lead to many wrong error messages in cases of options used in legal position but with syntactically invalid values (such as unterminated strings):
read file -file '~/my-data.json
In these cases, the parser produced a message:
Options must be specified before filter expressions.
This is clearly wrong because there are no filter expressions in play here.
The …
> Grammar: Remove hack detecting options after filter expressions

- lib/runtime/groups.js
- lib/runtime/reducers.js
- lib/runtime/values.js
- test/runtime/procs.spec.js
- test/runtime/specs/juttle-spec/reducers/count_unique-reducer.spec.md
Add support for grouping on and unique-counting of 'nested points', i.e. points whose fields can be objects or arrays.
This relies on serializing such fields using `values.inspect` into an unique string representation. This is not optimal from the memory consumption perspective, but should be OK as a first version.
Also, as the `values.valueOf` is now unused, remove it from the codebase.
refs: https://github.com/juttle/juttle/issues/55
> Reduce on nested

- lib/program.js
- lib/runtime/procs/base.js
- lib/runtime/procs/procs.js
All adapters and sinks descend from the Juttle.procs.sink class,
so tests whether a certain proc can rely on that, instead of explicitly
testing an `isSink` boolean flag.
Also fix circular dependency problem between base.js using Juttle.procs
and procs.js requiring base by assigning Juttle to module.exports early.
> Replace checks for isSink with inheritance test

- lib/parser/juttle-parser.js
Small set of refactoring I started before Christmas already. The idea is to make `parser.parse` more understandable.
Once this PR gets in, I’ll follow with a similar set of changes for `parser.parseSync`.
Part of work on #140.
> Parser cleanups: Tidy up `parser.parse`

- lib/parser/juttle-parser.js
This makes `parser.parseSync` a mirror image of `parser.parse`.
Part of work on #140.
> Parser cleanups: Tidy up `parser.parseSync`

- lib/runtime/values.js
Explicitly state that the representation of each Juttle value is unique.
> values: Improve `values.inspect` comment

- lib/adapters/http/write.js
These calls are noops (because `Write` is a sink).
See #131.
> HTTP adapter: Eliminate useless `emit_eof` calls in `Write`

- docs/adapters/http.md
- docs/examples/adapters/http_npm_download_counts.juttle
- lib/adapters/http/read.js
- lib/adapters/parsers/json.js
- test/adapters/http.spec.js
- test/adapters/parsers/input/json/point_with_nested_array.json
- test/adapters/parsers/json.spec.js
Add a `-rootPath` option to `read http` that can specify a path into the retrieved object from which the points should be processed.
Fixes #146.
> http adapter -rootPath option

- README.md
Although the docs are available within the github repository itself,
it seems useful to have a link to the external docs site generated
with mkthedocs.
> README: add a link to the docs site

- test/adapters/serializers/csv.spec.js
- test/adapters/serializers/json.spec.js
- test/adapters/serializers/jsonl.spec.js
Fixes issue #152
The issue was not waiting for the `open` event on the new writable
stream before attempting to verify the file was there and contained
anything that was recently written to it.
> fix timing bug in serializer tests

- lib/runtime/procs/uniq.js
- test/runtime/specs/juttle-spec/juttle-procs-uniq.spec.md
Add support for nested fields to `uniq` proc, by comparing values using `values.equal`.
refs: #55
> Uniq on nested fields

- lib/views/table.js
- lib/views/text.js
To output nested points, use `toString` serialization defined in `values.js`.
For csv text view, output arrays and objects in 'inspect' format, as the
brackets give a little bit more context while parsing the output
visually.
> Update views to handle nested points

- lib/compiler/build.js
- lib/compiler/graph-compiler.js
- lib/compiler/index.js
- lib/program.js
Pass Juttle runtime as an explicit dependency to code evaluated in the `flowgraph` and `eval` stages of the compiler. This means this code does not depend on the `juttle` variable being present in the evaluation context. The change will allow making other dependencies such as `JuttleMoment` explicit too in the future.
> Consolidate Juttle runtime: Pass Juttle runtime as a dependency

- lib/parser/juttle-parser.js
> parser: Avoid module recursion in parser.parse{Value,Filter}

- lib/runtime/adapters.js
Because adapters pull in the Juttle runtime via require('juttle/lib/xyz'),
there's a chance that loading an adapter may load another copy of the runtime
code, depending on the specifics of how the user installed the various node
modules.
This causes problems if identical code is loaded from two different paths,
since `instanceof` will fail to match an object created from one copy to the
class definition in another copy.
To avoid these issues, before loading the adapter, intercept the node.js
module loader and if there is a conflict for juttle, log an informative
error and exit the process.
If the environment variable JUTTLE_RESOLVE_ADAPTER_CONFLICT exists, then
log a warning and rewrite any require requests for `juttle/*` to be relative
paths using the _current_ module (i.e. …
> adapters: avoid loading multiple copies of juttle

- lib/compiler/ast-visitor.js
- lib/compiler/graph-compiler.js
- lib/compiler/optimize/optimize.js
- lib/parser/parser.pegjs
- lib/runtime/adapters.js
- lib/strings/juttle-error-strings-en-US.json
- test/runtime/adapter.spec.js
Add a check to the flowgraph build stage that makes sure an adapter with the
specified name is either registered or configured to be dynamically loaded.
As part of this change, modify the ast for read and write in order to preserve
the location information for the adapter name.
Relates to #83
> adapters: check for valid adapters in the build stage

- lib/moment/juttle-moment.js
This new option is used for creating a JuttleMoment duration from the native string representation of a momentjs moment.duration.
Will be used by outrigger for instantiating JuttleMoment durations from momentjs moment.duration.
@demmer
> JuttleMoment: new constructor option: rawDurationString

- lib/moment/juttle-moment.js
- lib/runtime/values.js
- test/runtime/values.spec.js
To be consistent with `values.js` compare and simplify the
implementation a bit, make `compare` for JuttleMoments return -1, 0, 1
for smaller, equal, or greater values.
Update the helper functions (`lt` / `gt`...) to handle new return values.
> JuttleMoment compare returns -1, 0, 1

- lib/runtime/juttle-utils.js
- test/runtime/juttle-utils.spec.js
Nested fields can contain juttle moments, which fromNative should
serialize to a string. Modify the conversion code to recursively
serialize object/array elements and add test.
Fixes: #172
> FromNative handles nested time fields

- lib/views/text.js
With the #200 in, remove the previously used workaround and simply rely on `toString`.
Fixes: #185
> Fix displaying of objects and arrays in the table view

- test/runtime/procs.spec.js
Previously the test could fail if :now: ended up aligned exactly on
a second boundary since the emitter would not send out the same
number of points as it did when :now: was not an exact second.
Change the test so that both start and end are quantized to the even
second so this isn't a problem.
Fixes #181
> test: tweak test to be more resilient to timing

- misc/emacs/juttle-derived-mode.el
Now that we have rendezvous, update the emacs "build" command to use
outrigger-client push, which is our preferred way of pushing programs
into juttled.
This fixes #198.
@mnibecker
> Update emacs make cmd to use outrigger-client.

- lib/views/table.js
- lib/views/text.js
Views should properly handle all Juttle data types by themselves, there is no need for the conversion.
> Purge utils.fromNative from views

- lib/runtime/procs/procs.js
- test/compiler/views_sourceinfo.spec.js
- test/runtime/sinks.spec.js
Emit view options as they are, instead of converting moments to JS Dates and moment durations to seconds.
This is necessary as part of the work we are doing with jsdp so browser views can be instantiated with real values (instead of numeric or string representations) on the other side of the websocket.
@dmajda cc @demmer
> view options: don't use convert_options

- lib/adapters/serializers/csv.js
Serialize array/object values using JSON, to keep point structure flat
and processable by CSV writer.
> CSV stdio serializer supports arrays/objects

- package.json
fixes #225
due to issues in a package dependency of node-grok this is a quick fix
to depend on our own fixed version of the node-grok source.
> updating to our own node-grok fork

- CHANGELOG.md
- package.json
This PR contains changes needed for 0.3.1:
* Copy of the fix for #225
* `CHANGELOG.md` update
The PR is against the `0.3.x` branch started off the `v0.3.0` tag. The idea is to release `0.3.1` off this branch instead of master in order to avoid carrying any other changes than the fix.
> Changes for 0.3.1

- test/runtime/specs/juttle-spec/juttle-spec.spec.md
- test/spec/juttle-spec.js
When generating test expectation, `util.inspect` was used with the default
level of depth 2. This lead to fake test failures when the expected
object was deeper than that and its values were represented by a
placeholder, e.g. `[Object]` or `[Array]`.
Pass `depth: null` parameter to `util.inspect` for infinite depth.
> juttle-spec: Fix handling of nested arrays/objects

- lib/runtime/juttle-utils.js
- lib/runtime/values.js
- test/runtime/values.spec.js
Converting juttle values to JSON compatible representation occurs
frequently enough to warrant a 'canonical' implementation.
Add `values.toJSONCompatible` and switch `JuttleUtils.fromNative` to use it.
refs: #209
> To json compatible

- lib/compiler/semantic.js
- lib/runtime/errors.js
- lib/runtime/modules/index.js
- lib/runtime/modules/json.js
- test/runtime/specs/juttle-spec/modules/json/parse.spec.md
- test/runtime/specs/juttle-spec/modules/json/stringify.spec.md
A draft for implementing Json module for Juttle.
The reasoning behind introducing a `Json` module is that adapters can produce serialised JSON values, which the user might want to parse, e.g. in the cases when the JSON type cannot be inferred from the schema.
There are two open questions:
1. how should we report parse errors from JSON parser? As a warning?
2. there seems to be a bug in juttle-spec dealing with nested objects, as mocha outputs (this can be observed when running the tests):
```
-      {
-        "key": "value"
-      }
+      [
+        [Function]
+      ]
```
> Add json module

- README.md
As suggested by @mccanne, change the paragraph in the readme
that talks about docs to have links to the external docs site and not
the source markdown files.
> README: update with external docs site links

- gulpfile.js
- test/runtime/test-adapter.js
we were missing lint checking on a few `.js` files in test that were
not `.spec.js` files so lets make sure to cover those.
> add all .js files to test lint checking

- docs/adapters/http_server.md
- docs/adapters/index.md
- lib/adapters/http_server.js
- test/adapters/http_server.spec.js
Some follow up fixes/improvements from @davidvgalbraith comments in pr #224.
All these pertain to the `http_server` adapter. Here's the skinny
- Added support for `-rootPath` option
- Fix improperly scoped `format` variable
- Use `Promise.try` instead of a million try/catch blocks.
- Add link to `http_server` documentation, in adapter index
> Http server fixes

- lib/adapters/http_server.js
- test/adapters/http_server.spec.js
Stop using hard-coded ports in the http server test since they're causing travis flakiness, and instead grab a free port for each test case.
Note that I tried grabbing a single free port for the whole test suite, but it seemed like there were still races in which one test case wouldn't release the port before the next one started, so I just used a simple beforeEach() to grab a new one each time.
> http_server: use a free port for each test

- lib/adapters/parsers/json.js
fixes #258
we were not correctly returning `oboe.drop` while using oboe to steam
JSON objects and therefore oboe was holding onto the references to each
of the parsed JSON objects and eventually blowing up as identified in
the issue #258
> fix memory leak in JSON parser

- lib/compiler/filters/filter-checker.js
- lib/compiler/graph-builder.js
- lib/compiler/semantic.js
Inputs of type `filter` produce `FilterLiteral` AST nodes that need to be semantically checked before they are compiled as part of a filter. The check is needed mainly to convert any `Variable` nodes into field
references (`UnaryExpression` nodes with `*` as the operator).
Until now, these checks were done in `FilterChecker` after `FilterLiteral` nodes coming from input values were embedded into filter expressions used by procs in the build phase. This was not ideal for two reasons:
1. `FilterChecker` is not supposed to modify checked filter AST, but applying a semantic check to `FilterLiteral`s did modify it.
2. We want to check the `FilterLiteral` itself, not its (possible many) embeddings.
This commit addresses the problems by moving the semantic check to `GraphBuilder` and applying it …
> filters: Don’t semantically check FilterLiterals in FilterChecker

- lib/compiler/filters/filter-checker.js
- lib/messages.json
- test/runtime/specs/juttle-spec/filter-expressions/expression-filter-terms.spec.md
`FilterChecker` was a bit of a spaghetti code which was hard to orient in. This commit rewrites it in more declarative style and makes it driven by a table of allowed forms for each operator. Beside making the code easier to follow this solution is more flexible and extensible (for example, it would be relatively easy to make the checks customizable for adapters).
The change doesn’t change the semantics of filter expressions in any way, but it changes some error messages (to the better, I hope).
Part of the work on #57.
> filters: Rewrite FilterChecker in more declarative style

- lib/runtime/juttle-utils.js
- test/runtime/juttle-utils.spec.js
So adapters can successfully convert points with time fields of type `Date` into points with `JuttleMoment`  values (for emitting into the flowgraph).
This does create some asymmetry between `toNative` and `fromNative` (which returns an ISO string for `JuttleMoment`). But `toNative` does already accept ISO strings _or_ number of seconds so being liberal in what we accept on the `toNative` side makes sense.
@davidvgalbraith @demmer
> juttle-utils#toNative: Convert JavaScript Date to JuttleMoment

- lib/compiler/graph-builder.js
- lib/graph.js
- lib/runtime/values.js
- test/runtime/values.spec.js
Implement `values.toAST` and `values.fromAST` functions which convert Juttle values from/to their AST representations. These functions replace ad-hoc, ugly, bug-ridden implementations of this functionality that we already had in the codebase.
The original motivation for this was getting rid of two lists of type display names ([in `values.js`](https://github.com/juttle/juttle/blob/612a8713a204ecb58255e1ed876e445613c86369/lib/runtime/values.js#L10-L21) and [in `filter-checker.js`](https://github.com/juttle/juttle/blob/master/lib/compiler/filters/filter-checker.js#L20-L33)). This will actually be done in a follow-up PR.
Vaguely related to #57.
> Implement Juttle value ↔ AST conversions

- lib/compiler/filters/filter-checker.js
Let’s clean up `FilterChecker` a bit before it is split up.
Part of the work on #57.
> Small FilterChecker cleanup

- lib/compiler/ast-visitor.js
The new place makes more sense and better corresponds to ordering used e.g. in `values.js` or `FilterJSCompiler`.
> ASTVisitor: Move FilterLiteral to other literals

- lib/adapters/http/index.js
- lib/adapters/http/optimize.js
- lib/adapters/http/read.js
- test/adapters/http.spec.js
fixes #276
expose the limit optimization that the `adapters/parsers` supports to
correctly optimize head when used with `read http`
> add head optimization to `read http`

- test/compiler/filters/filter-js-compiler.spec.js
Rewrite the `FilterJSCompiler` tests so that they don’t use ASTs, match structure of tested code better, and are more idiomatic. See individual commit messages for details.
Overall, these changes will make work with tests easier as capabilities of `FilterJSCompiler` are extended. 
Part of work on #57.
> Improve FilterJSCompiler tests

- lib/compiler/filters/filter-js-compiler.js
- test/compiler/filters/filter-js-compiler.spec.js
Extend `FilterJSCompiler` to handle AST nodes that will be part of dynamic filters. It can now handle essentially all expressions. The code was mostly adapted from `code-generator.js`, `build.js` and `graph-compiler.js` (and yes, it would be good to unify these instead of duplication — but that has to wait as we need to do more high-priority work now).
Note the chosen method of testing didn’t allow to test some expressions (e.g. function calls). These were noted in the test file and tested manually (with lifted filter checks). One way to test them would be to rewrite the tests into JuttleSpec, but that would make them much bigger and more clumsy so I didn’t want to do that (at least not now).
Part of work on #57.
> Extend FilterJSCompiler

- lib/compiler/filters/dynamic-filter-checker.js
- lib/compiler/filters/index.js
- lib/compiler/filters/static-filter-checker.js
- lib/compiler/graph-compiler.js
- test/compiler/inputs.spec.js
- test/runtime/specs/juttle-spec/filter-expressions/expression-filter-terms.spec.md
Split `FilterChecker` into `StaticFilterChecker` and `DynamicFilterChecker`, which are then tweaked and used in appropriate places in order to support dynamic filters in `filter`.
Final step of #57.
> Split FilterChecker and enable dynamic filters

- docs/adapters/http.md
- lib/adapters/http/read.js
- test/adapters/http.spec.js
fixes #287
by adding the `-format` option you can now overcome some of the
difficulties of dealing with services that don't always return the
right `content-type`.
> add -format to `read http`

- docs/adapters/file.md
- lib/adapters/file/write.js
- lib/adapters/serializers/base.js
- lib/adapters/serializers/csv.js
- lib/adapters/serializers/json.js
- lib/adapters/serializers/jsonl.js
- lib/adapters/stdio/write.js
- test/adapters/file/file.spec.js
- test/adapters/serializers/csv.spec.js
- test/adapters/serializers/json.spec.js
- test/adapters/serializers/jsonl.spec.js
- test/adapters/stdio/write.stdio.spec.js
fixes #125
remove the ability to append to a file when writing and simply rely on the
serializers to write out data in the various supported serializer formats.
we can revisit adding a `-append` option to the file adapter when it
becomes a requirement.
> expose -format for `write file`

- docs/sources/read.md
I noticed that our documentation on read was incorrect in terms of
how it distinguished adapter options from the filter expression.
I also updated the documentation on from / to / last to match the
new semantics.
> docs: fix up documentation on read

- .travis.yml
- lib/adapters/parsers/grok.js
- package.json
- test/adapters/file/file.spec.js
- test/adapters/parsers/grok.spec.js
- test/adapters/stdio/read.stdio.spec.js
- test/runtime/specs/juttle-test-utils.js
fixes #289
now node-grok will not be installed by npm and the user that has any
interest in using the grok parser will be prompted to install it
themselves (currently off our own fork).
> remove node-grok from the default juttle installation

- lib/program.js
- lib/runtime/procs/procs.js
- lib/runtime/procs/sink.js
- test/runtime/specs/juttle-test-utils.js
As the `TestView` was the last view depending on the pub sub system, modify it so it uses `program.events`. Then gradually remove dependencies on the `publish` and `subscribe` procs from the inheritance chains and from the code.
> Remove pubsub

- CONTRIBUTING.md
- README.md
- gulpfile.js
- lib/compiler/graph-compiler.js
- lib/compiler/index.js
- lib/program.js
- lib/runtime/adapters.js
- lib/runtime/ops.js
- lib/runtime/procs/stoke/util.js
- lib/runtime/values.js
- package.json
- test/runtime/specs/juttle-test-utils.js
After [moving to ESLint](https://github.com/juttle/juttle/pull/203) there still remained few places where JSHint and JSCS were referenced. Let’s eliminate them.
> ESLint move cleanups

- lib/compiler/code-generator.js
- lib/runtime/procs/read.js
- lib/runtime/procs/source.js
- lib/runtime/values.js
- test/compiler/filters/filter-js-compiler.spec.js
- test/compiler/views_sourceinfo.spec.js
- test/runtime/test-adapter-timeseries.js
- test/runtime/values.spec.js
- test/spec/input-default-functions.js
`JuttleMoment.duration` is not a constructor (just a factory function), so it should not be called using the `new` operator. This PR removes `new` from any such calls.
> Do not call JuttleMoment.duration with "new"

- lib/runtime/reducers.js
Instead of native javascript arithmetic operators, use `ops.add` and `ops.sub` in reducers. This ensures that the operations are type-checked and that adding incompatible types or types for which the operation is not defined, throws an error, instead of being silently converted.
> Values reducers

- lib/compiler/scope.js
- lib/runtime/procs/procs.js
- lib/runtime/runtime.js
Don't set `Juttle.reducers`. Instead, add reducers to the runtime and let compiled Juttle programs use them as `juttle.reducers.*`. This makes the programs less dependent on the `Juttle` variable.
> Don’t set Juttle.reducers

- lib/runtime/procs/procs.js
Anyone who needs to use `FilterJSCompiler` should require it directly.
Can be merged only after juttle/juttle-opentsdb-adapter#7 and juttle/juttle-sql-adapter-common#19 get merged.
> Consolidate Juttle runtime: Don’t set Juttle.FilterJSCompiler

- lib/adapters/http_server.js
- lib/compiler/autocompleter.js
- lib/compiler/graph-builder.js
- lib/compiler/graph-compiler.js
- lib/program.js
- lib/runtime/procs/base.js
- lib/runtime/procs/index.js
- lib/runtime/procs/pass.js
- lib/runtime/procs/procs.js
- lib/runtime/procs/view.js
- lib/runtime/runtime.js
Kill `Juttle.proc` after some preparatory refactoring. See individual commits for details.
Note the change set leaves `lib/runtime/procs/procs.js` in a weird state where it builds the `Juttle` object and has otherwise nothing to do with procs. I plan to dismantle that file completely over time.
> Consolidate Juttle runtime: Don’t set Juttle.proc

- test/adapters/file/file.spec.js
- test/adapters/http.spec.js
- test/adapters/http_server.spec.js
- test/adapters/stdio/read.stdio.spec.js
- test/adapters/stdio/write.stdio.spec.js
- test/runtime/adapter.spec.js
When testing that a juttle program ran with no errors or warnings,
use `expect(result.errors).deep.equals([])` instead of checking for
a zero-length array since in the event of a failure, it will actually
print what the errors are instead of uselessly reporting that some
error happened but not indicating what error it was.
> test: fix checks for no errors / warnings

- lib/compiler/semantic.js
- test/runtime/specs/juttle-spec/expressions/function-call.spec.md
For a function with single required argument, the total number of
arguments would be computed as NaN.
This was caused by the value of the field holding optional number
of arguments being 'undefined' and the addition with an integer
converting the result into NaN.
Fix: #328
> semantic.js - fix function arg count

- lib/messages.json
- lib/runtime/procs/periodic_funcs.js
- test/runtime/batch.spec.js
- test/runtime/specs/juttle-spec/juttle-procs-reduce.spec.md
When a reducer would process out-of-order points, it drops them and
correctly emits a warning. However, the message is misleading. E.g.:
```
read ... | reduce -every :2s: avg=avg(value) by pop
```
would result in:
"Warning: batch dropped out-of-order point(s)"
although there is no `batch` present. Change the wording to include
the proc name, so the above warning is more precise:
"out-of-order point(s) dropped by reduce"
Fix: #330
> Fix error message in reducer ooo point drop

- bin/juttle
- docs/modules/index.md
- docs/modules/juttle.md
- lib/compiler/semantic.js
- lib/runtime/adapters.js
- lib/runtime/modules/juttle.js
- test/runtime/juttle-module.spec.js
Add an `adapters.list()` API function that exposes the list of configured adapters with their versions and paths on disk.
Expose this as a constant array in the `Juttle` module so it can be printed by a simple program like:
```
emit -points Juttle.adapters
┌─────────────┬───────────────────────────────────────────┬─────────┐
│ adapter     │ path                                      │ version │
├─────────────┼───────────────────────────────────────────┼─────────┤
│ influx      │ /root/juttle-influx-adapter/index.js      │ 0.3.0   │
├─────────────┼───────────────────────────────────────────┼─────────┤
│ elastic     │ /root/juttle-elastic-adapter/lib/index.js │ 0.4.0   │
├─────────────┼───────────────────────────────────────────┼─────────┤
│ file        │ …
```
> expose the list of adapters to the runtime

- lib/messages.json
- lib/runtime/procs/base.js
- test/runtime/adapter-read-timeseries.spec.js
fixes #322
make sure to validate the -from/-to options passed to the read adapters
are never equal and if they are throw an appropriate error.
> verify that -from/-to are not equal in read adapters

- lib/compiler/index.js
- lib/program.js
- lib/runtime/procs/base.js
- lib/runtime/procs/view.js
- lib/views/table.js
- lib/views/text.js
- lib/views/view-mgr.js
- lib/views/view.js
- package.json
- test/runtime/specs/juttle-test-utils.js
Go through the handful of places where we were using Backbone.Events
in juttle and replace with eventemitter3.
This required changing all calls from `events.trigger` to `events.emit`.
Note that the procs still contain a method `this.trigger` to send the
event as compared to `this.emit` which emits points.
Also instead of attaching the event emitter functions to the program
object that's shared between the procs, attach a handle on the event
emitter itself, changing all callers from `program.trigger` to
`program.events.emit`.
Note that there are a couple of places where we still use the native
node EventEmitter -- that should be cleaned up separately.
Partially fixes #49
> events: replace backbone.Events with eventemitter3

- lib/adapters/parsers/base.js
- lib/adapters/parsers/csv.js
- lib/adapters/parsers/grok.js
- lib/adapters/parsers/json.js
- lib/adapters/parsers/jsonl.js
- lib/adapters/serializers/base.js
- lib/adapters/serializers/csv.js
- lib/adapters/serializers/json.js
- lib/adapters/serializers/jsonl.js
The parser / serializer base classes were the only places where we used the builtin node event emitter, so for consistency, use eventemitter3.
Along the way, clean up the way that we define all the parser / serializer classes to be more consistent and to pave the way for the big ES6 class conversion in #326.
Finishes up #49
> replace builtin node events with eventemitter3

- lib/compiler/ast-visitor.js
- lib/compiler/build.js
- lib/compiler/filters/filter-js-compiler.js
- lib/compiler/filters/partial-filter-js-compiler.js
- lib/compiler/filters/static-filter-checker.js
- lib/compiler/flowgraph/program_stats.js
- lib/compiler/graph-compiler.js
- lib/compiler/semantic.js
- lib/parser/parser.pegjs
- test/compiler/filters/filter-js-compiler.spec.js
- test/runtime/specs/juttle-spec/parser/field-dereference-operator-ambiguity.spec.md
- test/runtime/types/filter.spec.js
Until now, field references in expressions like `a < 5` or `#b > 6` were represented as `UnaryExpression` nodes with `*` as an operator and a `StringLiteral` with the field name as an expression. The idea behind this was that they are a syntax sugar for field dereference (the canonical form being `*'a' < 5` or `*'b' > 6`).
The `UnaryExpression` representation proved cumbersome to handle, especially in adapter code dealing with static filter expressions. Therefore, this commit gives field references more first-class status, representing them as `Field` nodes.
All relevant places are updated to handle the new nodes (the code is usually taken from `UnaryExpression` handling).
Note that changes done in `StaticFilterChecker` mean that expressions like `*'a' < 5` are no longer considered valid …
> Filters simplify field reference representation

- lib/adapters/file/read.js
- lib/adapters/file/write.js
- lib/adapters/http/read.js
- lib/adapters/http/write.js
- lib/messages.json
- lib/runtime/adapter-read.js
- lib/runtime/adapter-write.js
- lib/runtime/procs/base.js
- lib/runtime/procs/read.js
- lib/runtime/procs/write.js
- test/runtime/adapter.spec.js
- test/runtime/test-adapter.js
Also, we don't currently check allowed options for adapter write unless the `allowedOptions` method is overwritten, which is inconsistent with what we do for `read`. So let's check them.
@juttle/developers
> adapters: check required options in base

- lib/adapters/http_server.js
- lib/runtime/adapter-read.js
- lib/runtime/adapter-write.js
- lib/runtime/procs/read.js
- test/adapters/http_server.spec.js
Port the http_server adapter to the new adapter API.
In addition to changes to the adapter itself, this also exposed some issues and limitations in the base class:
- Add wrappers for compileError and runtimeError to the adapter read/write base classes. This is not strictly required for the port, but rather than change the adapter to explicitly call errors.compileError, I figured we would need these for per-adapter error codes as described in #59.
- Add a teardown hook for read so the adapter can clean up properly.
- Add simple eof tracking to read. This avoids sending multiple eof's downstream and also as a workaround for the limitation that we can't currently cancel pending scheduler callbacks.
> http server adapter port to the new adapter api

- lib/runtime/procs/oops_funcs.js
- test/runtime/specs/juttle-spec/juttle-procs-put.spec.md
- test/runtime/specs/juttle-spec/juttle-procs-reduce.spec.md
This behavior makes handling of invalid time assignment consistent with handling of other runtime errors such as type errors.
Fixes #358 & #359.
> Make assigning invalid time in put/reduce produce a warning

- lib/runtime/procs/fanin.js
- test/runtime/specs/juttle-spec/flowgraph-tests.spec.md
Change a test probing for presence of the `time` field in a point so that a `null` value is treated as if the `time` field was not set. This is in line with other similar checks in the codebase. The end result is that points with `null` time don’t cause an exception.
Fixes #351.
> fanin: Handle null time field in incoming points

- package.json
- test/adapters/file/read.spec.js
- test/adapters/http.spec.js
- test/adapters/parsers/csv.spec.js
- test/adapters/parsers/grok.spec.js
- test/adapters/parsers/json.spec.js
- test/adapters/parsers/jsonl.spec.js
- test/adapters/serializers/csv.spec.js
- test/adapters/serializers/json.spec.js
- test/adapters/serializers/jsonl.spec.js
- test/adapters/stochastic.spec.js
I wanted to use [`.keys`](http://chaijs.com/api/bdd/#keys) in a test and found I couldn’t because we use an awfully old version of `chai`.
> Use chai 3.5.0

- lib/compiler/graph-compiler.js
- lib/runtime/procs/base.js
Pretty much just mooching off of @demmer's work in https://github.com/juttle/juttle/pull/334 and the to-be-reviewed https://github.com/juttle/juttle/pull/364.
Previously, `pname` was attached to proc instances at `this.pname`, but that was removed in https://github.com/juttle/juttle/pull/154.
I was using the proc's `pname` in [juttle-flowgraph-viz](https://github.com/juttle/juttle-flowgraph-viz) when monkey-patching [emit](https://github.com/juttle/juttle-flowgraph-viz/blob/848f5333611165568c36d5d9d1d8d3f33453d553/src/app.js#L16-L25) to do a "join" between the node emitting the points and its entry in the flowgraph JSON.
@dmajda cc @demmer
> pass pname in proc params and attach params to proc instance

- lib/program.js
- lib/runtime/procs/procs.js
Inline `Juttle.teardown` into `Program#deactivate`. Move `Juttle.visitGen` into `Program#visitGen`.
This is a little step on the path leading to dismantling the `Juttle` global object.
> Consolidate Juttle runtime: Kill Juttle.visitGen and Juttle.teardown

- lib/runtime/procs/read.js
- lib/runtime/procs/write.js
All adapters should already be converted or should be converted
soon to use the new adapter API, so remove the hacks in read / write
that supported the "old" contract in which adapters directly
implement source / sink procs.
Connects to #369
> adapters: remove the read/write shims for legacy adapters

- lib/runtime/procs/batch.js
- lib/runtime/procs/emit.js
- lib/runtime/procs/fanin.js
- lib/runtime/procs/filter.js
- lib/runtime/procs/head.js
- lib/runtime/procs/join.js
- lib/runtime/procs/keep.js
- lib/runtime/procs/oops-fanin.js
- lib/runtime/procs/pace.js
- lib/runtime/procs/periodic-fanin.js
- lib/runtime/procs/put.js
- lib/runtime/procs/read.js
- lib/runtime/procs/reduce.js
- lib/runtime/procs/remove.js
- lib/runtime/procs/sequence.js
- lib/runtime/procs/sink.js
- lib/runtime/procs/skip.js
- lib/runtime/procs/sort.js
- lib/runtime/procs/source.js
- lib/runtime/procs/split.js
- lib/runtime/procs/tail.js
- lib/runtime/procs/uniq.js
- lib/runtime/procs/view.js
- lib/runtime/procs/write.js
- lib/views/file.js
- lib/views/table.js
- lib/views/text.js
All these changes were previously reviewed as part of the move to ES6 classes in #326.
This set of changes cleans up the inheritance of reduce to no longer use mixins and normalizes the constructor arguments for procs / views.
> clean up inheritance

- CONTRIBUTING.md
- README.md
- docs/concepts/inputs.md
- docs/concepts/overview.md
- docs/reference/cli.md
- docs/sinks/view.md
- misc/emacs/juttle-derived-mode.el
Replace the links to the outrigger project with links to juttle-engine.
Note: this is to merge into the 0.4.x branch, to be included in a 0.4.1 release of juttle.
> docs: update links to point to juttle-engine and not outrigger

- lib/errors.js
- lib/runtime/types/juttle-moment.js
- lib/views/file.js
- lib/views/table.js
- lib/views/text.js
- lib/views/view.js
- test/spec/juttle-spec.js
Clean up various places in the code we use properties attached to the prototype or mixins of functions directly attached to the prototype instead of regular class inheritance.
This is to pave the way for ES6 classes (#326) without requiring the use of getter functions.
@dmajda
> no more prototype properties

- lib/messages.json
- lib/runtime/modules/date.js
- lib/runtime/types/juttle-moment.js
- test/runtime/specs/juttle-spec/modules/date/new.spec.md
- test/runtime/specs/juttle-spec/modules/date/parse.spec.md
- test/runtime/types/moments.spec.js
Date module's `new` wasn't catching errors from JuttleMoment properly and JuttleMoment's parse error wasn't that much descriptive either.
Catch and re-throw JuttleMoment's generic `Error` as Juttle native errors and also improve the error message wording.
> Date parsing errors

- bin/juttle
- lib/cli/log-setup.js
- test/cli/cli.spec.js
- test/cli/util.js
If the DEBUG environment variable is present, support setting the
named targets to debug level, or * for all targets.
Fixes #373.
> logging: configure log targets through DEBUG environment variable

- lib/compiler/graph-compiler.js
- lib/runtime/procs/procs.js
`Juttle.extend_options` was a helper function responsible for processing proc options — specifically expanding nested options and `-o`/`-options`. So far it did its work in runtime but there is no good reason for that (options are known in compile-time already).
This PR moves `Juttle.extend_options` into `GraphCompiler`, which runs it in compile-time. Note the move required making it work on AST nodes instead of Juttle values.
> Consolidate Juttle runtime: Move Juttle.extend_options to the compiler

- lib/compiler/graph-compiler.js
- lib/runtime/procs/procs.js
- lib/runtime/procs/view.js
Move `Juttle.channels` to program (the object generated by compiler and passed to procs).
This is a little step on the path leading to dismantling the `Juttle` global object.
> Consolidate Juttle runtime: Kill Juttle.channels

- package.json
To workaround an npm problem in which it sometimes refuses to run the
postinstall script, change the package so that it generates the parser
in the prepublish phase and not postinstall.
This also required explicitly enumerating the files to be put into the
package since by default it omits anything that's in .gitignore, but we
want it to include the generated files in the package.
> package.json: change scripts/peg.js to run in prepublish not postinstall

- bin/juttle
- lib/compiler/optimize/optimize.js
- lib/runtime/procs/procs.js
- test/runtime/specs/juttle-test-utils.js
Just use the `adapters` module directly where it is needed.
This is a little step on the path leading to dismantling the `Juttle` global object.
**This change will require adapting the adapters.**
> Kill Juttle.adapters

- lib/program.js
There's no need to delete this.graph here (as far as I can tell), and by not deleting
it we enable tests that call deactivate() to validate graphs.
@juttle/developers @dmajda
> program: don't delete this.graph in deactivate

- lib/compiler/ast-visitor.js
- lib/compiler/build.js
- lib/compiler/code-generator.js
- lib/compiler/filters/filter-js-compiler.js
- lib/compiler/filters/static-filter-checker.js
- lib/compiler/graph-compiler.js
- lib/compiler/semantic.js
- lib/parser/parser.pegjs
- lib/runtime/types/filter.js
- lib/runtime/values.js
- test/cli/location-stripper.spec.js
- test/compiler/filters/filter-js-compiler.spec.js
- test/compiler/inputs.spec.js
- test/parser.spec.js
- test/runtime/types/filter.spec.js
- test/runtime/values.spec.js
Small cleanups of AST nodes representing literals. They can get passed to adapters as part of filter expression AST so they form a part of the adapter API. The idea of this PR is to stabilize this part of the API and reduce need of future changes here.
Part of work on #319.
> Filters AST cleanups (part 1)

- lib/compiler/ast-visitor.js
- lib/compiler/build.js
- lib/compiler/filters/filter-js-compiler.js
- lib/compiler/graph-compiler.js
- lib/compiler/semantic.js
- lib/parser/parser.pegjs
- test/compiler/filters/filter-js-compiler.spec.js
Small cleanups mostly involving the `PropertyAccess` node. As [before](https://github.com/juttle/juttle/pull/406), the idea is to stabilize filter AST sent to adapters.
Part of work on #319.
> Filters AST cleanups (part 2)

- lib/views/table.js
- test/cli/cli.spec.js
The bug was actually that table titles were not being written when
-progressive was set to false. It just happens that when specifying
multiple tables, -progressive gets set to false by default.
Use the right option (self.options.title) instead of self.title.
Also add a test to cover this so we'll know if it breaks again.
This fixes #350.
@dmehra
> Write table properly for multiple tables.

- README.md
Add links to juttle-aws-adapter/juttle-cloudwatch-adapter.
@dmehra @rlgomes
> Add AWS/Cloudwatch references.

- lib/adapters/stdio/read.js
- lib/runtime/procs/read.js
- test/runtime/test-adapter.js
Instead of requiring the adapter to create an infinite JuttleMoment
to indicate that it's done reading, also check for an eof bit in the
read() response.
> adapters: support an explicit eof bit in the read return

- docs/adapters/file.md
- lib/adapters/file/write.js
- test/adapters/file/write.spec.js
fixes #286
simple change to make `-append` option available for the file adapter
which only works currently with csv and jsonl.
> enable append for file adapter on write

- test/adapters/parsers/csv.spec.js
- test/adapters/parsers/grok.spec.js
fixes #403
we were not waiting for the callback from the `stream.end()` call and
therefore there was a very small window of time where we could have
partially written out data to the file and would fail to read back all
of the expected data.
> fix flakey grok test

- lib/compiler/ast-transformer.js
- lib/compiler/ast-visitor.js
- lib/compiler/filters/filter-js-compiler.js
- lib/compiler/filters/filter-simplifier.js
- lib/compiler/graph-compiler.js
- test/compiler/ast-transformer.spec.js
- test/compiler/filters/filter-js-compiler.spec.js
- test/compiler/filters/filter-simplifier.spec.js
Simplify filter expression AST before it is passed to a compiler. More specifically:
1. Remove `ExpressionFilterTerm` nodes (which the compiler typically just passes-through).
2. Replace `SimpleFilterTerm` nodes which contain `StringLiteral` (and thus represent FTS) with structurally simpler `FulltextFilterTerm` nodes.
3. Replace `SimpleFilterTerm` nodes which contain `FilterLiteral` (and thus represent embedded filter expression coming from an input ) with the actual `FilterLiteral` AST (effectively inlining the literal).
These transformations are done using `FilterSimplifier`, which is an instance of newly introduced `ASTTransformer` — a special kind of visitor which transforms the tree.
Part of work on #320.
> Simplify Filter AST

- lib/compiler/filters/static-filter-compiler.js
- lib/messages.json
- test/compiler/filters/filter-js-compiler.spec.js
- test/compiler/filters/process-filter.js
- test/compiler/filters/static-filter-compiler.spec.js
`StaticFilterCompiler` is a base class for compilers that transform filter expression ASTs into native queries, to be inherited and extended by adapters.
Part of work on #320.
> Implement StaticFilterCompiler

- lib/compiler/build.js
- lib/compiler/code-generator.js
- lib/compiler/graph-compiler.js
- lib/compiler/semantic.js
The new name is more logical and it is in line with most other code which processes AST nodes.
This is a small step toward #394, #395, and #396.
> Rename the “ast” parameter to “node” in various compiler passes

- lib/runtime/procs/oops-fanin.js
warn_oops was called without arguments from emit_mark, which caused an
error masking the actuall out-of-order problem
> oops-fanin.js: Fix args passing to warn_oops

- lib/compiler/graph-builder.js
- lib/compiler/semantic.js
- test/compiler/filters/process-filter.js
The semantics pass was somewhat schizophrenic: its methods modified AST nodes in-place, but they also returned them, which would normally suggest a functional interface without in-place modifications.
This commit bends semantic pass internals firmly toward the in-place modification side, getting rid of node returns and fixing all places where returned nodes were used. The other alternative was to keep the returns and modify the code to work in functional style, always returning new nodes. This would complicate the code, cause performance problems, and provide little overall benefit, so I decided not to go this way, despite its apparent elegance.
One disadvantage of this approach is that `sa_Variable` and `sa_reducer_arg`, which created new nodes, now have to modify the existing ones, …
> SemanticPass: Do not return nodes

- lib/runtime/procs/periodic-fanin.js
- lib/runtime/procs/reduce.js
- lib/stdlib/predict.juttle
- test/runtime/specs/juttle-spec/juttle-procs-reduce-paranoia.spec.md
- test/runtime/specs/juttle-spec/juttle-procs-reduce.spec.md
- test/runtime/specs/juttle-spec/reducers/delta-reducer.spec.md
`reduce -every` emits marks at the end of each epoch. This also requires changes for sort and tests that depend on the old behavior.
> Make reduce -every emit marks at the end of epoch

- lib/runtime/procs/fanin.js
Improve readability of fanin's 'input with earliest point' selection.
Commit refactoring the `earliest` loop will be squashed - they were kept separate for easier review.
> Fanin readability

- lib/compiler/build.js
- lib/compiler/graph-builder.js
- lib/compiler/graph-compiler.js
- lib/compiler/scope.js
- lib/compiler/semantic.js
The semantic pass added two properties to `Variable` and `MemberExpression` nodes:
* `uname` — unique name of the variable or module export, to be used in compiled code
* `symbol` — symbol table entry for the variable or module export
Since the symbol table entry already contained the unique name, setting the `uname` property on the nodes was redundant, and I decided to remove the `uname` assignment. Note this makes a lot of sense conceptually — the unique name is a property of the referenced object (variable, function, reducer,…), not of the reference to it, so it belongs to its symbol table entry, not to the node referencing it.
During the work it turned out that `uname` is also set for nodes which *define* symbols, such as `FunctionDef` or `ReducerDef`. I decided to make these …
> SemanticPass: Kill unames (almost)

- lib/parser/parser.pegjs
- test/runtime/sinks.spec.js
- test/runtime/specs/juttle-spec/inputs/options.spec.md
- test/runtime/specs/juttle-spec/procs/options.spec.md
- test/runtime/specs/juttle-spec/views/options.spec.md
Before this commit, option values were parsed using the `ByList` rule. This was an easy way to parse multi-value options, but it meant the parser returned multiple values as `ByList` nodes, which triggered
coercion rules for `by` clauses in the semantic pass. This was undesirable.
This commit changes the grammar to parse options using a new `OptionValue` rule which returns multiple option values as `ArrayLiteral` nodes. These don’t trigger coercion in the semantic pass.
Note the change also means options no longer auto-flatten their values (this was another side effect of using `ByList`). I think this is OK — the behavior was surprising and it probably needs some tweaking even in case of `by` clauses.
Fixes #444.
> Do not coerce identifiers in multi-value options to strings

- lib/adapters/api.js
`ASTTransformer` can be used by adapters which transform filter AST before processing, e.g. the InfluxDB adapter.
`StaticFilterCompiler` is the new base class for filter compilers.
Related to #320.
> Add ASTTransformer and StaticFilterCompiler to adapter API

- docs/adapters/http.md
- lib/adapters/http/read.js
- package.json
- test/adapters/http/read.spec.js
- test/adapters/http/test-server.js
partially fixes #195
added the option `-followLinkHeader` to http read adapter that allows
for automatic following of the HTTP Link header as described in
https://tools.ietf.org/html/rfc5988
> add followLinkHeader to read adapter

- lib/compiler/scope.js
- lib/compiler/semantic.js
The high-level idea of this PR is to stop using the `opts` parameter to pass context around in the semantic pass and replace it by instance variables.
In general, passing context around using a parameter leads to unnecessarily verbose code and [can lead to performance problems](https://github.com/pegjs/pegjs/commit/cdeecf750f8a3f781459ed817815a537392993c1) when done properly (the context ends up being copied often so that child nodes don’t modify parents’ context).
In the particular case of semantic pass, the `opts` parameter was also used inconsistently, which made related code was brittle and bug-prone. Using an instance variable ensures the context is defined everywhere and is set in more controlled manner.
Note the instance variables and helper methods introduced in this PR probably …
> Semantic: Kill “opts”

- lib/errors.js
- test/runtime/types/errors.spec.js
As a side-effect of changing from extendable-base to ES6 classes, and
due to the fact that the `message` property is not enumerable when
passed to the Error constructor, the message wasn't actually included
in the JSON representation of an Error.
To fix this, add a toJSON implementation that explicitly enumerates
message, code, and info. This does not include the name of the error
class, which makes things compatible with how they were in juttle 0.4
and earlier.
> error: add toJSON so that message is included when serializing

- lib/compiler/semantic.js
- lib/messages.json
- test/runtime/basic-language.spec.js
Previously, defining an empty sub resulted in the following error from
the compiler:
```
$ bin/juttle -e 'sub s() {}; s'
Error: Cannot read property 'head' of undefined
```
As the sub didn't contain any nodes, it didn't return any which the
compiler could attach into the surrounding flowgraph.
A simple fix is to regard empty subs as an error. This is consistent
with handling of an empty program / flowgraph.
Fixes: #433
> semantic.js - disallow empty subs

- lib/runtime/procs/read.js
- lib/runtime/procs/write.js
Lets validate options before initializing the the `read` or `write` proc.
Why? Because sometimes the `read` or `write` proc constructors need to use validated options.
> validate options before init read or write proc

- bin/juttle
- lib/runtime/adapters.js
- test/runtime/juttle-module.spec.js
In order to improve the ability of embedders like juttle-service
to list the version of all adapters, add the module name and a flag
to indicate which ones are builtins to the adapter list.
> adapters: add the module name and builtin flag to the adapter list

- README.md
Add "new" built-in adapters (stdio/http_server) to top level README.
@rlgomes @dmajda @mnibecker @go-oleg
> Add new built-in adapters to top README.

- lib/compiler/graph-compiler.js
- lib/compiler/index.js
- lib/program.js
The high level goal of this patch set is to make `scheduler` accessible during procs construction.
Currently, procs access a `program` object and its properties, some of which (e.g assignments for `channels` and `now`) are generated by the compiler.
After the code produced by the compiler is evaluated, additional properties (`scheduler`) are assigned to `program`.
And as a part of `activate` step, the `program` object is further extended with `env` and `events` properties.
Instead of generating `program` in the compiler, then extending it in various ways, pass instance of `Program` class to the compiler and ensure that all properties required by procs are added during `Program`'s `constructor` call. This also makes them accessible during compilation phase.
> Program cleanups

- lib/compiler/semantic.js
This should have been done in caf4cf8821712fa016aa8279d094bd88567eb3e0.
> SemanticPass: Remove use of obsolete allow_field_comparisons option

- lib/runtime/modules/boolean.js
- lib/runtime/modules/date.js
- lib/runtime/modules/duration.js
- lib/runtime/modules/null.js
- lib/runtime/modules/number.js
- lib/runtime/modules/regexp.js
- lib/runtime/modules/string.js
Various `toString` functions in Juttle modules implemented their own string representation of Juttle values. Let’s replace that with `values.toString`, which is the canonical way.
(The reason why `toString` functions did their own thing is that there was no `values.toString` when they were written.)
> Make toString functions in Juttle modules use values.toString

- lib/compiler/build.js
- lib/compiler/filters/filter-js-compiler.js
- lib/compiler/graph-compiler.js
- lib/compiler/semantic.js
Various preparations for making the `.` operator work properly in rvalues. Core changes are splitting lvalue and rvalue processing in the semantic pass (so they can be refactored independently) and preparing the compiler for the existence of dynamic non-computed member expressions (that is, expressions like `foo.bar` where `foo` is not a module).
> Make the “.” operator work properly in rvalues (part 1)

- bin/juttle
- lib/compiler/flowgraph/check_runaway.js
- lib/parser/parser.pegjs
- test/compiler/flowgraph/check_runaway.spec.js
- test/runtime/specs/juttle-test-utils.js
fixes #245
add in the runaway program detector and revive the unit tests along with
a small tweak to the pegjs grammar to correctly populate the sort proc
name
> plugin runaway program detector

- docs/adapters/adapter_api.md
- mkdocs.yml
First cut at describing the adapter API.
Resolves #304.
> docs: add first cut adapter implementation API doc

- lib/compiler/semantic.js
- test/runtime/basic-language.spec.js
In this part, `sa_MemberExpression` is cleaned up so that future change to support dynamic non-computed member expressions could be done easily. As a nice side effect, error messages in case of invalid module entity references (e.g. `m.c` when there is no module `m` imported) are improved.
Note that both lvalue and rvalue branches are affected by the changes (they are still kept identical). Splitting them in #488 was apparently slightly premature, but I realized that too late and didn’t want to go back and do a big rebase at the time.
> Make the “.” operator work properly in rvalues (part 2)

- lib/compiler/semantic.js
- test/runtime/specs/juttle-spec/expressions/dot-operator-rvalue-entities.spec.md
- test/runtime/specs/juttle-spec/expressions/dot-operator-rvalue-modules.spec.md
- test/runtime/specs/juttle-spec/expressions/dot-operator-rvalue-values.spec.md
This commit adds tests that specify behavior of the `.` operator in rvalues and adjusts the implementation to match. Specifically, it allows using the `.` operator not only to access entities exported from
modules, but also properties of objects.
> Make the “.” operator work properly in rvalues (part 3)

- bin/juttle
Caught this through code inspection but we're already setting the default for an implicit view to be `table`  [here](https://github.com/juttle/juttle/blob/master/lib/compiler/flowgraph/implicit_views.js#L9) so no need for this code.
> remove unnecessary setting of table default

- lib/parser/parser.pegjs
- test/runtime/specs/juttle-spec/filter-expressions/expression-filter-terms.spec.md
- test/runtime/specs/juttle-spec/parser/field-dereference-operator-ambiguity.spec.md
Without this syntax, there was no way to enter field names containing special characters.
The implementation is done directly in parser and it converts the `*"field"` syntax directly to `Field` nodes (instead of `UnaryExpression` nodes). This makes the syntax transparent for any filter processing code and ensures only string literal arguments of `*` are allowed.
Fixes #483.
> Allow *"field" syntax in static filter expressions

- lib/adapters/http/read.js
- lib/messages.json
- test/adapters/http/read.spec.js
fixes #465
move the response to a `.body` field and placing the HTTP status message
into the actual `error.message` will make the UI's that display this
error not have to deal with large or ugly looking response payloads.
> fix http error handling

- lib/runtime/errors.js
- lib/runtime/values.js
- test/runtime/values.spec.js
The test verifying that typeErrorIncomparable was thrown for comparison
of two incomparable value types wasn't checking for an actual error
string.
This masked an incorrect bind and another problem with cyclical
dependenncy between `lib/runtime/errors.js` and `lib/runtime/values.js`.
Fix the bind and break the cycle by moving the error helper into
`values.js` - it is not used anywhere else.
> values.spec.js - fix incorrect bind in "invalid comparison" test

- lib/compiler/semantic.js
Refactor `sa_CallExpression` in order to eliminate duplication and to prepare for moving bulk of the symbol-manipulating an checking code to `sa_Variable` and `sa_MemberExpression`.
> Refactor sa_CallExpression

- docs/adapters/http.md
- docs/examples/adapters/http_travisci_builds.juttle
- lib/adapters/http/read.js
- lib/messages.json
- test/adapters/http/read.spec.js
- test/adapters/http/test-server.js
While working on pulling TravisCI build statuses, I found I needed an
additional pagination method.
The pagination format TravisCI uses is:
https://api.travis-ci.org/repos/juttle/juttle/builds?after_number=<id>
after_number is related to a number field in the results:
{..., number: <id>, ...}
The idea is that you fetch the first page, find the last build number,
and then ask for another page with all builds after <id>.
To support that, add a new option for -pageUnit, "field". When
-pageUnit=field, an additional new option pageField is required, which
controls the field to use from the last returned point as the value to
put in the subsequent request's pageParam.
When pageUnit = field, the initial request does not contain a
pageParam query parameter.
Within the read adapter, the iterator …
> Add support for new paging method using after query params.

- bin/juttle
- test/adapters/http/read.spec.js
- test/adapters/http_server.spec.js
- test/adapters/stochastic.spec.js
- test/compiler/flowgraph/check_runaway.spec.js
- test/runtime/adapter-read-timeseries.spec.js
- test/runtime/specs/juttle-test-utils.js
- test/spec/juttle-spec.js
Procs and scheduler depend on the program deactivation after juttle runs
and not doing that can lead to leaking timers.
Fix calls to `run_juttle` or `program.activate` that were missing a
corresponding `program.deactivate` call.
> Deactivate program after running it

- lib/compiler/ast-visitor.js
- lib/parser/parser.pegjs
Update the grammar so that it generates AST nodes with `type: 'Identifier'` wherever we generate identifiers that contain locations.
This involved replacing instances of the `Identifier` rule with the functionally equivalent `IdentifierName`, and changing `IdentifierNameWithPos` to be the new `Identifier` which creates the appropriate AST nodes.
Fixes #507
> ast-visitor handle adapters

- test/runtime/specs/juttle-spec/parser/field-dereference-operator-ambiguity.spec.md
One of the tests was relying on stochastic adapter emitting a certain
number of points and was failing non-deterministically.
Either the bug is in reduce, or in stochastic adapter (which is known to
sometimes emit ooo points that are automatically dropped).
From the syntax POV, an adapter is an easy place to trigger the
ambiguity which we want to test, i.e. to get a number/duration literal
nearby a field dereference.
Change the adapter from stochastic to test and modify the irrelevant
test condition that was counting points to be stable.
Fixes: #525
> Star operator ambiguity tests use test adapter

- test/adapters/http_server.spec.js
- test/runtime/specs/juttle-test-utils.js
The change in #522 called deactivate immediately after running the
program unless deactivateAfter was set, which is the wrong semantics
since it will cause the programs to terminate early.
Instead, when deactivateAfter isn't set, wait until the program is
done before calling deactivate.
Also fix the call to Promise.delay -- the delay time is supposed to
be the only argument in bluebird promises.
> juttle-test-utils: by default deactivate after the program is done

- docs/adapters/http.md
- lib/adapters/http/read.js
- test/adapters/http/read.spec.js
Address feedback from Mike on https://github.com/juttle/juttle/pull/524 after I merged:
- Make pageField and pageStart exclusive, adding a new unit test to check.
- Change the docs to only mention the exclusivity for pageField.
There's still a bad interaction with
https://github.com/juttle/juttle/commit/167935e3f5e66cc3862e890fc707efd4ab076a8e. Test
programs are calling deactivate immediately and relying on active
reads to signal that the program should be torn down. That doesn't
work for any of these paging based methods that could involve multiple
calls to read.
> More improvements to field based paging.

- docs/adapters/adapter_api.md
Take most of the general discussion from the gmail adapter docs at
https://github.com/juttle/juttle-gmail-adapter/blob/master/docs/adapter_impl_notes.md
and add them to this doc. Specifically, added the following:
- How juttle loads an adapter
- General discussion of live/historical and how that relates to the data read/written by an adapter.
- Notes on configuration.
- Options supported by many read commands.
- Notes on the filter expression and how its parsed version is made available to the adapter.
- Notes on write and expectations for write (don't block event loop) and eof (return a promise that resolves when everything is written).
- Logging
- Returning errors.
Once this is merged I'll change the gmail adapter docs to take out the
general stuff and tailor it more closely to the …
> Add more detail on how to write adapters.

- lib/compiler/build.js
- lib/compiler/graph-compiler.js
- lib/compiler/semantic.js
`Build` and `GraphCompiler` checked that entities such as module references or functions were not used as variables. This check was semantic in nature so this PR moves it to the semantic pass. See the commit messages for more details.
> Move variable checks from Build and GraphCompiler to SemanticPass

- lib/runtime/procs/reduce.js
- test/runtime/specs/juttle-spec/juttle-procs-reduce.spec.md
To be consistent with `batch | reduce`, `reduce -every` should emit an
initial mark at the start of first batch.
Fixes #537, #538
> reduce.js - emit initial mark on first batch start

- lib/runtime/procs/reduce.js
- test/runtime/specs/juttle-spec/juttle-procs-reduce.spec.md
`reduce_batch` advances on `eof`, thus emitting the aggregate on empty flow,
i.e. when there aren't any upstream points, only an `eof`.
Make `reduce -every` follow the same pattern.
Fixes: #516
> reduce.js - reduce -every returns aggregates for empty set of points

- lib/compiler/semantic.js
- test/runtime/specs/juttle-spec/expressions/variable.spec.md
Variable checks in the semantic were incomplete. For example, the compiler correctly reported that `f` can’t be used as a variable in cases like this:
function f() {
}
const c = f[0];
but not in cases like this:
function f() {
}
const c = (f + 1)[0];
This was because the `in_member_expression` flag wasn’t reset back to `false` when processing expressions deeper in `MemberExpression`’s object.
This PR fixes that and also generalizes the flag a bit in anticipation of upcoming refactorings.
Part of work on #419 (really a fix to #544).
> Fix moved variable checks

- bin/juttle
- gulpfile.js
- lib/compiler/flowgraph/implicit_views.js
- lib/compiler/index.js
- test/runtime/graph-api.spec.js
- test/runtime/object-literals.spec.js
- test/runtime/sinks.spec.js
- test/runtime/specs/juttle-test-utils.js
fixes #494
set the list of default processors while making sure to pass the
`options.implicit_view` which allows the underlying `implicit_view`
processor to change its default behavior at runtime.
> default processors for compiler

- lib/compiler/scope.js
- lib/compiler/semantic.js
- test/runtime/modules.spec.js
fixes #520
quick fix and test to verify that we throw an error when the user
accidentally imports a module with the same locally scoped identifier.
> throw an error when redefining a module import

- bin/juttle
- lib/runtime/procs/emit.js
- test/cli/cli.spec.js
- test/cli/util.js
Allow ctrl-c to stop programs by adding a signal handler for SIGINT
that calls program.deactivate(). bin/juttle must also set standard
input to non-raw mode while the program is running so ctrl-c isn't
read by the cli directly.
Read already handles teardown properly in a limited way--after any
pending read has completed, the adapter is torn down and emits an
eof. An in-progress read is not stopped, though.
Emit required changes, though--add a teardown method that sets
a flag. The next time run() is called, it checks the flag and emits
eof() if set.
With these changes, a program won't be stopped until the next emit
happens or a read in progress has completed. If we want immediate
program cancellation, we'd have to make some additional changes:
- Modify the scheduler to return ids from all …
> Allow ctrl-c to stop programs (politely)

- lib/compiler/scope.js
- lib/compiler/semantic.js
- lib/messages.json
- test/runtime/basic-language.spec.js
- test/runtime/specs/juttle-spec/expressions/dot-operator-rvalue-modules.spec.md
This is basically the same thing as #561, just for `MemberExpression`. This concludes refactoring of `sa_CallExpression`, which now doesn’t contain various symbol-manipulating and symbol-checking code that doesn’t belong there and relies fully on `sa_Variable` and `sa_MemberExpression` to handle this.
A nice side effect of the change is fixing several incorrect error messages.
> SemanticPass: Call sa_MemberExpression in sa_CallExpression

- lib/compiler/index.js
Currently, passing an empty array as a value of the `fg_processors` option causes the compiler to run the default processors. That shouldn’t be the case, it should simply run no processors. This commit fixes the compiler to do just that.
> compiler: Fix fg_processors processing when an empty array is passed

- CONTRIBUTING.md
- README.md
- docs/adapters/adapter_api.md
- docs/concepts/programming_constructs.md
- docs/doc_templates/template.md
- docs/index.md
- docs/juttle_ecosystem.md
- docs/reference/data_types.md
- lib/compiler/build.js
- lib/compiler/graph-compiler.js
- lib/compiler/semantic.js
- lib/config/read-config.js
- test/runtime/basic-language.spec.js
- test/runtime/specs/juttle-spec/modules/math.spec.md
Change from Javascript to JavaScript. As far as I can tell, this is _the_ accepted way to spell/capitalize it.
@mstemm @dmajda
> fix JavaScript capitalization

- lib/compiler/flowgraph/check_runaway.js
fixes #577
the old message was way off topic suggesting to use a `-to` when the
fact is that you simply need to make your read range time bound or batch
the underlying stream
> change the runaway error message to something more useful

- gulpfile.js
Recent increase of functions coverage threshold to 92% (#533) broke at least one refactoring-only PR (#573) with another one suspected (#566). Let’s revert the change.
> gulpfile.js: Lower functions coverage threshold to 91%

- gulpfile.js
Turns out that #579 wasn’t enough and #573 still [fails on Node 5.x](https://travis-ci.org/juttle/juttle/jobs/115269310). Let’s lower more numbers.
> gulpfile.js: Lower statements & lines coverage threshold to 92%

- lib/runtime/procs/base.js
- lib/runtime/procs/batch.js
- lib/runtime/procs/fanin.js
- lib/runtime/procs/head.js
- lib/runtime/procs/join.js
- lib/runtime/procs/oops-fanin.js
- lib/runtime/procs/pace.js
- lib/runtime/procs/periodic-fanin.js
- lib/runtime/procs/put.js
- lib/runtime/procs/reduce.js
- lib/runtime/procs/skip.js
- lib/runtime/procs/sort.js
- lib/runtime/procs/tail.js
- lib/runtime/procs/unbatch.js
- lib/runtime/procs/uniq.js
- lib/runtime/procs/view.js
- lib/views/text.js
- lib/views/view-mgr.js
- lib/views/view.js
- test/runtime/specs/juttle-test-utils.js
So far, marks were represented as a simple scalar value - time.
As a preparation for adding `interval` info into marks, change marks to
be objects, with `time` property containing the time stamp.
Modify all procs to create and access the `time` property, rename `time`
parameter of `consume_mark/emit_mark/mark` methods to `mark` and update
views to receive the complete mark object via the `view:mark` event, not
just time.
> Represent marks as objects

- lib/compiler/scope.js
- lib/compiler/semantic.js
- test/runtime/basic-language.spec.js
The idea is the same as in refactoring of `sa_CallExpression` (#515, #561, #566) — rely on `sa_Variable` and `sa_MemberExpression` for symbol processing and avoid duplicating it in `sa_FunctionProc`.
A nice side effect of the change is fixing an incorrect error message.
> SemanticPass: Refactor sa_FunctionProc

- lib/runtime/procs/read.js
If an error occurs as part of the read implementation, it's useful
to have the full stack trace as context when logging at debug level.
> read: include the full stack trace in the debug log on a read error

- .travis.yml
- lib/adapters/parsers/grok.js
fixes #213
we no longer have to depend on our own fork containing a fix and can
correctly rely on node-grok from npm
> use node-grok from npm

- lib/parser/parser.pegjs
- test/runtime/specs/juttle-spec/expressions/assignment-expression.spec.md
This change brings assignment expressions closer to assignment statements which already support indexed assignment.
Part of work on #426.
> Support indexed assignment in assignment expressions

- lib/compiler/build.js
- lib/compiler/graph-compiler.js
- lib/compiler/semantic.js
- lib/parser/parser.pegjs
- test/runtime/specs/juttle-spec/statements/assignment-statement.spec.md
Adds support for `*=`, `/=`, `%=`, `+=`, `-=`, `<<=`, `>>=`, `>>>=`, `&=`, `^=`, and `|=`.
This change brings assignment statements closer to assignment expressions, which already support these assignment operators.
Part of work on #426.
> Support more operators in assignment statements

- lib/compiler/semantic.js
- lib/messages.json
- lib/parser/parser.pegjs
Instead of treating function calls specially in the grammar, handle them similarly to `[]` and `.` operators — that is, allow any expression before `()` and leave it to the semantic pass to decide whether this expression is callable or not.
> Generalize function call grammar

- lib/compiler/semantic.js
- test/runtime/specs/juttle-spec/expressions/star-operator.spec.md
Consider an expression like this:
```juttle
*field = "foo"
```
The `field` variable is evaluated and its value is used to select a point field. It is not itself assigned to. In semantic pass, this corresponds to processing with `this.lhs == false`.
Before this commit, code in `sa_UnaryExpression` wrongly processed `*` arguments with the same `this.lhs` value as the operator itself. This PR fixes it to always process them with `this.lhs == false`.
Fixes #598.
> Fix processing of argument of the “*” operator

- test/runtime/specs/juttle-spec/expressions/dot-operator-rvalue-nested.spec.md
- test/runtime/specs/juttle-spec/expressions/get-operator-rvalue-nested.spec.md
Just to make sure this situation is covered.
> Add nested expression tests for “.” and “[]” operators

- lib/compiler/build.js
- lib/compiler/graph-compiler.js
- lib/compiler/semantic.js
Assignment LHS was handled specially both in the semantic pass and in later compiler stages. This was  bad design which was largely unnecessary with the current compiler structure. This PR removes all traces of this special handling and makes it so that assignments are handled mostly like all other expressions.
> Generalize assignment LHS handling

- test/runtime/specs/juttle-spec/expressions/function-call.spec.md
- test/runtime/specs/juttle-spec/filter-expressions/and-operator.spec.md
- test/runtime/specs/juttle-spec/filter-expressions/or-operator.spec.md
- test/runtime/specs/juttle-spec/juttle-calendar-moments.spec.md
- test/runtime/specs/juttle-spec/juttle-procs-filter.spec.md
- test/runtime/specs/juttle-spec/juttle-procs-put.spec.md
- test/runtime/specs/juttle-spec/juttle-procs-reduce.spec.md
- test/runtime/specs/juttle-spec/juttle-procs-sort.spec.md
- test/runtime/specs/juttle-spec/juttle-stochastic-adapter.spec.md
- test/runtime/specs/juttle-spec/optimization/optimize-tail.spec.md
- test/runtime/specs/juttle-spec/stdlib/select.spec.md
- test/spec/juttle-spec.js
Require tests to emit # of warnings / errors equal to the number of errors / warnings expected.
This also changes the semantics of juttle-spec's assertions. A missing errors/warnings section no longer means 'any number of errors', but 'no errors'.
Fix tests that were broken by this change.
> Stronger juttle spec assertions

- lib/compiler/scope.js
- lib/compiler/semantic.js
This PR rewrites mutability checks in the semantic pass as symbol checks. This is the right thing conceptually, it leads to more straightforward code, it avoids repeated symbol lookups, and it paves the path for allowing nested member assignments.
> Rewrite mutability checks in the semantic pass

- lib/runtime/procs/reduce.js
- lib/stdlib/predict.juttle
- test/runtime/specs/juttle-spec/juttle-procs-reduce-paranoia.spec.md
- test/runtime/specs/juttle-spec/juttle-procs-reduce.spec.md
- test/runtime/specs/juttle-spec/reducers/delta-reducer.spec.md
Revert 'reduce -every emits marks' work. Should fix #594.
Commits which are plain reverts reference the reverted ones, those which had to be updated do not.
> Revert reduce every emits marks

- lib/runtime/procs/pace.js
This was used in Jut 1.0 times and is not that relevant anymore.
As the logic is complex, the behavior unintuitive (and there is also a
bug with unitialized `data_t0` when `-from` is not passed), drop the
feature.
Fix: #608
> pace.js - remove decelerate towards realtime rate feature

- bin/juttle
- docs/concepts/programming_constructs.md
- docs/examples/concepts/import_module_from_stdlib.juttle
- docs/examples/concepts/import_module_nested.juttle
- docs/examples/concepts/shared/module.juttle
- docs/examples/concepts/shared/second_module.juttle
- gulpfile.js
- lib/cli/errors.js
- lib/module-resolvers/file-resolver.js
- lib/module-resolvers/resolver-utils.js
- lib/parser/index.js
- test/cli/cli.spec.js
- test/module-resolvers/file-resolver.spec.js
- test/runtime/juttles/index.juttle
- test/runtime/juttles/subdir/index.juttle
- test/runtime/juttles/subdir/subdir2/index.juttle
- test/runtime/juttles/subdir/updir_module.juttle
- test/runtime/modules.spec.js
See commits for specific changes.
I'd like feedback on the technique of modifying the ast to handle the case of potentially duplicate import statements with the same relative pathname. Not sure whether this is bad practice or not.
One open question--do we want imports of standard library modules to have a 'stdlib' prefix? Currently, the stdlib directory is in the set of search paths so one imports those files with a 'import "random" as random" rather than 'import "stdlib/random". I think I'd have to move the lib/stdlib directory somewhere as a part of this change--we don't want lib/ as a search path.
@demmer @dmajda 
This fixes #513.
> Add support for importing using relative paths

- lib/compiler/build.js
- lib/compiler/graph-compiler.js
- lib/compiler/semantic.js
- lib/messages.json
- lib/runtime/errors.js
- lib/runtime/ops.js
- package.json
- test/runtime/specs/juttle-spec/expressions/get-operator-lvalue-entities.spec.md
- test/runtime/specs/juttle-spec/expressions/get-operator-lvalue-nested.spec.md
- test/runtime/specs/juttle-spec/expressions/get-operator-lvalue-values.spec.md
After some preparatory work, this PR adds tests that specify behavior of the `[]` operator in lvalues and adjusts the implementation to match. Specifically, it adds missing type checks and allows modification of expressions not associated with a symbol (which enables nested member assignment).
Note that member assignment in `put`/`reduce` still isn't allowed. Making it work requires more substantial changes which will be done later.
> Make the “[]” operator work properly in lvalues

- lib/compiler/flowgraph/implicit_views.js
- lib/compiler/optimize/optimize.js
- lib/graph.js
- test/runtime/adapter.spec.js
- test/runtime/graph-api.spec.js
- test/runtime/test-adapter/index.js
Now that reduce -every doesn't emit marks, we don't want optimized
reduce -every to do so either.
This reverts commit 4742fe12ac2463d5d32f2dcf3b50346dba7726da.
Reverts #499 
Fixes #594 
@davidvgalbraith
> Revert "add a batch"

- lib/compiler/scope.js
- lib/compiler/semantic.js
- lib/parser/parser.pegjs
- test/runtime/specs/juttle-spec/expressions/dot-operator-lvalue-entities.spec.md
- test/runtime/specs/juttle-spec/expressions/dot-operator-lvalue-nested.spec.md
- test/runtime/specs/juttle-spec/expressions/dot-operator-lvalue-values.spec.md
This PR adds tests that specify behavior of the `.` operator in lvalues and adjusts the implementation to match. Specifically, it extends the Juttle grammar and removes incorrect checks in the semantic pass.
Note that member assignment in `put`/`reduce` still isn't allowed. Making it work requires more substantial changes which will be done later.
> Make the “.” operator work properly in lvalues

- lib/compiler/graph-compiler.js
- lib/parser/parser.pegjs
- lib/runtime/procs/oops-fanin.js
- lib/runtime/procs/reduce.js
- test/runtime/specs/juttle-spec/expressions/dot-operator-lvalue-entities.spec.md
- test/runtime/specs/juttle-spec/expressions/get-operator-lvalue-entities.spec.md
Implement nested field assignment in `put`/`reduce`. This means code like this is completely valid now and works (assuming the `a` field contains appropriate Juttle value):
```juttle
put a[0].b[0] = 1
```
Final part for work on #419.
> Implement nested field assignment

- lib/compiler/optimize/optimize.js
- lib/compiler/optimize/optimize_sort.js
- test/runtime/adapter.spec.js
- test/runtime/test-adapter/index.js
Adapters can optimize `reduce`, `head`, and `tail` procs.
This PR will allow adapters to optimize sort. Full example here: https://github.com/juttle/juttle-sql-adapter-common/pull/55
> allow adapter sort optimization

- docs/adapters/adapter_api.md
- docs/concepts/programming_constructs.md
- lib/adapters/api.js
- lib/module-resolvers/file-resolver.js
- lib/runtime/adapters.js
- test/module-resolvers/file-resolver.spec.js
- test/runtime/juttle-module.spec.js
- test/runtime/test-adapter/juttle/index.juttle
This adds support for per-adapter modules.
Should I bump the juttle api version for this? Following semver we'd want it to be 0.6.0, but maybe we could cheat and make it 0.5.3 instead.
After this merges I'll update the aws adapter and adapter template to provide examples.
This fixes #325.
@demmer @dmajda
> Add adapter modules

- bin/juttle
- lib/cli/errors.js
Instead of assuming that any error with a location is a Juttle Error,
use instanceof JuttleError instead.
This means we should only call show_in_context when the error has a
location, and just generically print the error otherwise.
This fixes #563.
@dmajda @rlgomes
> Use instanceOf JuttleError to identify Juttle Errors.

- bin/juttle
- test/cli/cli.spec.js
fixes #575
fixed by making sure we reject any program that had errors at runtime
with the exact error being sent back as part of the promise rejection.
> make the cli exit with non zero exit code on failure

- lib/compiler/semantic.js
- test/runtime/specs/juttle-spec/reducer-args.spec.md
Before this PR, variables passed as reducer args were coerced into fields unless there was a const or var in scope with the same name. All other entities such as functions or reducers were ignored. This was inconsistent with by-lists and sort-lists where coercion in such cases lead to a `CANNOT-USE-AS-VARIABLE` error.
This PR makes coercion of reducer args work exactly the same as in by-lists and sort-lists (by utilizing the same code path).
Fixes #646.
> SemanticPass: Fix reducer args coercion

- lib/compiler/flowgraph/views_sourceinfo.js
- test/compiler/flowgraph/views_sourceinfo.spec.js
- test/runtime/object-literals.spec.js
- test/runtime/sinks.spec.js
Previously we were grabbing from/last/to info from 'read' nodes. Grab the info from 'emit' as well.
Removed `_jut_time_bounds` verification from some tests because it felt a bit redundant.
@dmajda @bkutil @demmer
> views_sourceinfo: get info from 'emit' nodes

- lib/runtime/procs/view.js
- lib/views/view-mgr.js
- test/runtime/specs/juttle-test-utils.js
For 'emit:mark', 'emit:tick', and 'emit:points' events, always put the payload for (e.g. mark, time, points) into a property called 'payload'.
The change in https://github.com/juttle/juttle/pull/567 requires making changes in a few places that receive marks and pass them on to somewhere else (https://github.com/juttle/juttle-service/issues/71 and https://github.com/juttle/juttle-client-library/issues/80). Since these places just pass-through the core payload of the event and only transform the surrounding event metadata, using a generic 'payload' allows us to future-proof against any changes we might make to the 'payload' contents. These intermediate steps shouldn't need to be changed every time - only the actual end-subscribers to the events (generally the views).
We can use 'data' …
> view.js: emit event payload in a consistently named property

- test/runtime/specs/juttle-spec/stdlib/predict.spec.md
- test/runtime/specs/juttle-spec/stdlib/random.spec.md
- test/runtime/specs/juttle-spec/stdlib/select.spec.md
- test/runtime/specs/juttle-spec/stdlib/stats.spec.md
- test/runtime/specs/juttle-test-utils.js
Modify the resolver used by juttle-test-utils, which takes a
collection of modules and falls back to stdlib otherwise, to use the
file resolver as a backup instead of looking under the stdlib
directory itself.
This allows import statements within unit tests to use short names for
stdlib modules if desired. It also allows other test programs (like
the aws unit tests) to also utilize adapter modules.
@rlgomes and @dmajda this is the change we discussed at https://github.com/juttle/juttle/pull/591#issuecomment-198086588.
> Fold file resolver into test resolver.

- lib/parser/parser.pegjs
- test/runtime/specs/juttle-spec/expressions/bitwise-not-operator.spec.md
- test/runtime/specs/juttle-spec/expressions/eager-logical-not-operator.spec.md
- test/runtime/specs/juttle-spec/expressions/short-circuiting-logical-not-operator.spec.md
- test/runtime/specs/juttle-spec/expressions/unary-minus-operator.spec.md
- test/runtime/specs/juttle-spec/expressions/unary-plus-operator.spec.md
Add missing check so that unary operators on string literals don’t behave like unary `*`.
Fixes #650.
> Juttle grammar: Fix handling of unary operators on string literals

- README.md
The website is already linked as part of github's repo's metadata but its placement at the top can be easy to miss:
@dmehra @demmer
> README: add link to project website

- lib/compiler/filters/static-filter-checker.js
- lib/compiler/filters/static-filter-compiler.js
- test/compiler/filters/static-filter-compiler.spec.js
- test/runtime/adapter.spec.js
- test/runtime/specs/juttle-spec/filter-expressions/expression-filter-terms.spec.md
The static filter checker rejects any read filters that
have property accesses. But these can be handled in some
cases (at least by Elastic), so let's allow them.
@juttle/developers
> filters: allow property accesses

- lib/adapters/api.js
- test/runtime/test-adapter-clone/package.json
- test/runtime/test-adapter-timeseries/package.json
- test/runtime/test-adapter/package.json
This is needed because #384 introduces an incompatible change.
> Bump adapter API version to 0.7.0

- CHANGELOG.md
Including this bug fix as a release as upstream tests in
juttle-service were relying on the fixed behavior.
@demmer @go-oleg
> Update for 0.7.1.

- docs/processors/sort.md
- lib/messages.json
- lib/runtime/procs/sort.js
- test/runtime/specs/juttle-spec/juttle-procs-sort.spec.md
Ideally, the warning you get when running a program with `sort` on large input, `Warning: sort limit exceeded, dropping points` would also include the value of the limit - asking @rlgomes to add that. Here, fixing the doc which was wrong.
> Report sort limit correctly

- lib/cli/errors.js
Instead of just showing the message for internal errors, show the full
stack. This also includes the error class and message, so it's
strictly more information than we were showing.
This fixes #564.
@dmajda @go-oleg @rlgomes
> Show stack for internal errors.

- docs/stdlib/select.md
- lib/stdlib/select.juttle
- test/runtime/specs/juttle-spec/stdlib/select.spec.md
fixes #388
added `top` & `bottom` subs along with necessary tests and documentation
> add top and bottom subs to select module in stdlib

- docs/stdlib/stats.md
- lib/stdlib/stats.juttle
- test/runtime/specs/juttle-spec/stdlib/stats.spec.md
found upon inspection of the stdlib and since we have a built-in stdev
implementation this is completely unnecessary
> remove duplicate implementation of stdev

- lib/cli/errors.js
- lib/parser/parser.pegjs
Add a description to `SortByList` in the grammar, and tweak the cli's handling of errors at the end of input to emit better errors when the user forgets to add a field for the sort:
```
<input>:1:12:
1:emit | sort
^
Error: Expected sort field(s) but end of input found. (SYNTAX-ERROR-WITH-EXPECTED)
<input>:1:13:
1:emit | sort | head
^
Error: Expected option or sort field(s) but "|" found. (SYNTAX-ERROR-WITH-EXPECTED)
```
@rlgomes @dmajda @mstemm
> improve sort no fields error

- lib/cli/log-setup.js
- lib/cli/stderr-appender.js
- test/cli/cli.spec.js
Use a custom log4js appender to send the logging output to stderr
instead of through console.log.
Fixes #637
> cli: send logging output to stderr instead of console

- bin/juttle
- docs/reference/cli.md
- lib/views/raw.js
- lib/views/view-mgr.js
- test/cli/cli.spec.js
In order to help debug a juttle program in the CLI that contains
visual sinks, add a --view-mode option to the cli which can be either "text" in
which case all views are rendered as text), or "raw" in which case it just
prints out the raw underling data that would go to the views over the
websocket.
@go-oleg @mstemm
> add a view mode to the cli to show either all text or raw

- lib/compiler/optimize/optimize_reduce.js
- lib/runtime/procs/read.js
- test/adapters/stochastic.spec.js
- test/runtime/adapter-read-timeseries.spec.js
- test/runtime/test-adapter-timeseries/index.js
If we're doing an optimized reduce -every live program, we should only make one query per
batch. We start by going from from to the end of the first batch, then each
subsequent query is made over a full batch.
Will fix https://github.com/juttle/juttle-elastic-adapter/issues/108
@demmer @VladVega
> read: quantize from/to for optimized reduce -every
