.travis.yml

when we opened up the juttle repo we stopped receiving slack
notifications from travis this should fix that

fix travis notifications

---

lib/compiler/optimize/optimize.js
lib/compiler/optimize/optimize_tail.js
test/runtime/specs/juttle-spec/optimization/optimize-tail.spec.md
test/runtime/test-adapter.js

Optimize tail

---

package.json
test/runtime/specs/juttle-spec/procs/emit.spec.md

Fix two tests that failed locally for me

---

lib/parser/juttle-parser.js

Parser cleanups: Final round

---

test/runtime/specs/juttle-spec/juttle-procs-join.spec.md

Join proc works without modifications for nested points (as it relies on groups, which have been already updated). Just add tests (tm).

Add tests for nested points in join proc

---

lib/errors.js

See individual commits for details.
Part of work on on #165.

Streamline error-related code

---

docs/concepts/fields.md
docs/examples/concepts/object_array_point_simple.juttle
docs/examples/concepts/object_reduce.juttle
docs/examples/concepts/object_uniq.juttle
docs/reference/data_types.md

Add documentation for nested fields

---

docs/adapters/file.md
docs/adapters/parsers/grok.md
docs/adapters/parsers/index.md
docs/adapters/stdio.md
gulpfile.js
lib/adapters/file/read.js
lib/adapters/parsers/base.js
lib/adapters/parsers/grok.js
lib/adapters/parsers/index.js
lib/adapters/stdio/read.js
lib/strings/juttle-error-strings-en-US.json
mkdocs.yml
package.json
test/adapters/file/file.spec.js
test/adapters/parsers/base.spec.js
test/adapters/parsers/grok.spec.js
test/adapters/parsers/input/logs/bad-syslog
test/adapters/parsers/input/logs/syslog
test/adapters/serializers/base.spec.js
test/adapters/stdio/read.stdio.spec.js

fixes #37 
with this we can now parse log lines using grok from the file and stdio
adapter

grok parser

---

docs/adapters/file.md
docs/adapters/parsers/grok.md
docs/adapters/parsers/index.md
docs/adapters/stdio.md

@rlgomes i believe you already approved.

Minor doc fixes to grok documentation

---

docs/concepts/filtering.md
lib/compiler/semantic.js
lib/strings/juttle-error-strings-en-US.json
test/runtime/specs/juttle-spec/filter-expressions/simple-filter-terms.spec.md

A couple of miscellaneous small changes fixing problems discovered during work on #56. Since they are only tangential to the core of the work I split them into their own PR.

Small FTS-related fixes

---

CHANGELOG.md
package.json

Merge changes from the `0.3.x` branch to master.

Merge 0.3.x changes

---

test/runtime/values.spec.js

values.js - Add tests for type checking

---

gulpfile.js

we seemed to have received another bump here so lets make sure to keep
the numbers up

updating coverage numbers

---

gulpfile.js

Revert "updating coverage numbers"

---

README.md

Update README.md with OpenTSDB adapter link

---

lib/adapters/stdio/index.js
lib/adapters/stdio/optimize.js
lib/adapters/stdio/read.js
test/adapters/stdio/read.stdio.spec.js

fixes #275
adding head optimization to stdio and added required tests.

add head optimization to `read stdio`

---

mkdocs.yml

Merging this so docs can be deployed with this new file.

Adding http server doc to the docs tree

---

lib/compiler/build.js
lib/compiler/code-generator.js
lib/compiler/filters/filter-js-compiler.js
lib/compiler/graph-builder.js
lib/compiler/graph-compiler.js
lib/compiler/index.js
lib/program.js
lib/runtime/runtime.js
lib/runtime/types.js

Make compiled Juttle programs independent on `JuttleMoment` and `Filter` variables.

Consolidate Juttle runtime: Independence on JuttleMoment and Filter

---

lib/program.js

Instead of checking a flag, check using instanceof

program.js - use inheritance check for view

---

lib/adapters/file/read.js
lib/adapters/file/write.js
lib/adapters/http/read.js
lib/adapters/http/write.js
lib/adapters/http_server.js
lib/adapters/stdio/read.js
lib/adapters/stdio/write.js
lib/adapters/stochastic.js
lib/runtime/adapter-read.js
lib/runtime/adapter-write.js
lib/runtime/procs/base.js
lib/runtime/procs/batch.js
lib/runtime/procs/emit.js
lib/runtime/procs/join.js
lib/runtime/procs/pace.js
lib/runtime/procs/put.js
lib/runtime/procs/read.js
lib/runtime/procs/reduce.js
lib/runtime/procs/split.js
lib/runtime/procs/view.js
lib/runtime/procs/write.js
test/adapters/http.spec.js
test/adapters/http_server.spec.js
test/runtime/adapter.spec.js
test/runtime/test-adapter-timeseries.js
test/runtime/test-adapter.js

adapters: validate options in base class

---

gulpfile.js

fixes #263
quick fix to simply make sure to monkeypatch things back at the end of
the gulp task so a subsequent task doesn't get the wrong adapters
method implementations

fix gulp task to correctly monkeypatch and unpatch things

---

.eslintrc

The code already conformed to all of these rules, so adding them
to prevent regression.

eslint: add a few additional rules

---

lib/messages.json
lib/runtime/procs/base.js
test/runtime/adapter-read-timeseries.spec.js

Reverts juttle/juttle#333
per comment on previous PR there was a better place to handle this.

Revert "verify that -from/-to are not equal in read adapters"

---

lib/adapters/file/read.js
lib/adapters/http/read.js
lib/runtime/adapter-read.js
lib/runtime/juttle-utils.js
test/adapters/http.spec.js

fixes #194 
preliminary version of how to do get this done and also expose the
functionality in a way that we can apply to other adapters with ease.

adding support for -from/-to to http adapter

---

docs/modules/index.md
mkdocs.yml

Correctly include the new Juttle module doc in the docs pages

---

lib/runtime/juttle-utils.js
test/adapters/file/read.spec.js
test/runtime/juttle-utils.spec.js

remove time field from data

---

CHANGELOG.md
package.json

Pull the 0.4.2 changes back to master.

merge 0.4.2 back to master

---

lib/compiler/index.js
lib/program.js
lib/runtime/index.js
lib/runtime/procs/procs.js

Consolidate Juttle runtime: Kill the Juttle global variable

---

lib/compiler/build.js

Make compiled programs independent on Underscore.js

---

lib/adapters/serializers/csv.js
lib/adapters/serializers/index.js
test/adapters/parsers/csv.spec.js
test/adapters/serializers/base.spec.js
test/adapters/serializers/csv.spec.js
test/adapters/serializers/jsonl.spec.js

fixes #346 
adding append feature into the serializers themselves.

append mode for serializers

---

lib/adapters/file/read.js
lib/adapters/http/read.js
lib/runtime/adapter-read.js
lib/runtime/procs/read.js
test/runtime/adapter-read-timeseries.spec.js
test/runtime/specs/juttle-test-utils.js
test/runtime/test-adapter-timeseries.js

defaultTimeRange becomes defaultTimeOptions, which includes
lag and every
fixes https://github.com/juttle/juttle/issues/308

adapters: specify default lag/every

---

lib/adapters/file/read.js
lib/adapters/http/read.js
lib/adapters/stdio/read.js
lib/adapters/stochastic.js
lib/runtime/adapter-read.js
test/runtime/test-adapter-timeseries.js
test/runtime/test-adapter.js

A couple of minor cleanups to avoid the use of ES6 getter functions.

adapter getter cleanup

---

lib/compiler/ast-visitor.js
lib/compiler/build.js
lib/compiler/filters/filter-js-compiler.js
lib/compiler/filters/partial-filter-js-compiler.js
lib/compiler/flowgraph/program_stats.js
lib/compiler/graph-compiler.js
lib/compiler/semantic.js
lib/parser/parser.pegjs
test/compiler/filters/filter-js-compiler.spec.js

Small cleanups involving various nodes. As [before](https://github.com/juttle/juttle/pull/406), the idea is to stabilize filter AST sent to adapters.
Part of work on #319.

Filters AST cleanups (part 3)

---

lib/compiler/ast-transformer.js

ASTTransformer should not overwrite ASTVisitor's prototype

Fix typo in ASTTransformer

---

lib/runtime/procs/base.js
lib/runtime/procs/emit.js

I was just reading through the named outputs code & design and added a few notes to emit.

Add comments to `_output` option in emit

---

lib/compiler/semantic.js
lib/runtime/modules/array.js
test/runtime/specs/juttle-spec/modules/array/concat.spec.md
test/runtime/specs/juttle-spec/modules/array/join.spec.md
test/runtime/specs/juttle-spec/modules/array/last-index-of.spec.md
test/runtime/specs/juttle-spec/modules/array/pop.spec.md
test/runtime/specs/juttle-spec/modules/array/push.spec.md
test/runtime/specs/juttle-spec/modules/array/reverse.spec.md
test/runtime/specs/juttle-spec/modules/array/shift.spec.md
test/runtime/specs/juttle-spec/modules/array/slice.spec.md
test/runtime/specs/juttle-spec/modules/array/sort.spec.md
test/runtime/specs/juttle-spec/modules/array/splice.spec.md
test/runtime/specs/juttle-spec/modules/array/to-string.spec.md
test/runtime/specs/juttle-spec/modules/array/unshift.spec.md

array: add the rest of the functions

---

lib/compiler/semantic.js
lib/runtime/modules/string.js
test/runtime/specs/juttle-spec/modules/string/char-at.spec.md
test/runtime/specs/juttle-spec/modules/string/char-code-at.spec.md
test/runtime/specs/juttle-spec/modules/string/from-char-code.spec.md
test/runtime/specs/juttle-spec/modules/string/match.spec.md
test/runtime/specs/juttle-spec/modules/string/trim.spec.md

relates to https://github.com/juttle/juttle/issues/58

string: add the rest of the functions

---

lib/compiler/semantic.js
lib/runtime/modules/object.js
test/runtime/specs/juttle-spec/modules/object/to-string.spec.md
test/runtime/specs/juttle-spec/modules/object/values.spec.md

- toString
- values
relates to https://github.com/juttle/juttle/issues/58
@dmajda @bkutil

object: add the rest of the functions

---

lib/compiler/semantic.js

SemanticPass: coerce_var-related cleanups

---

lib/compiler/semantic.js

SemanticPass: reducers-related cleanups

---

CHANGELOG.md
lib/errors.js
test/runtime/types/errors.spec.js

Backport bugfix for #467 and update changelog for 0.5.1

0.5.1 bugfixes

---

lib/adapters/api.js

Adapter API: add parsers/serializers

---

docs/reference/operators.md

operators.md - add documentation for escaping * and ? wildcards

---

CHANGELOG.md
lib/adapters/api.js
lib/errors.js
package.json
test/runtime/types/errors.spec.js

Sync up with the changes from the 0.5.x branch.

merge 0.5.2 back to master

---

lib/compiler/filters/filter-js-compiler.js
lib/compiler/semantic.js
test/runtime/specs/juttle-spec/expressions/function-call.spec.md

Fix function calls in filter expressions

---

README.md

Since the more complete installation of juttle will want to use
juttle-engine and not just the CLI, change the introduction and
installation instructions to refer to both options.

README: update to make juttle-engine more prominent

---

lib/compiler/flowgraph/implicit_views.js
lib/compiler/optimize/optimize.js
lib/graph.js
test/runtime/adapter.spec.js
test/runtime/graph-api.spec.js
test/runtime/test-adapter/index.js

Total hack! Best way to solve this problem though if we insist on the marks thing.
@demmer @dmajda @bkutil 
fixes https://github.com/juttle/juttle/issues/484

optimizer: add a batch after reduce -every

---

gulpfile.js

Noticed that our coverage numbers had gone up a tiny bit so lets  not lose the coverage.

updating the coverage numbers

---

lib/compiler/filters/static-filter-checker.js
lib/messages.json
test/runtime/specs/juttle-spec/filter-expressions/expression-filter-terms.spec.md

Disallow filtering on time in static filter expressions

---

lib/compiler/flowgraph/check_runaway.js
test/compiler/flowgraph/check_runaway.spec.js

fixes #572
pretty straightforward change to make sure we pass location information
along with the error when detecting a runaway program

add location informationt to runaway errors

---

lib/adapters/file/read.js

Add an iterator so that the points are emitted in chunks instead
of waiting until the full file is parsed.

file: change read so that it emits points in batches

---

docs/adapters/file.md
docs/adapters/stdio.md

with #584 we added the ability to specify a separator so lets document
how to use this option

updated stdio and file adapter documentation

---

README.md
docs/concepts/juttle_tutorial.md

Fixing up the tutorial, not for merge yet, but for @demmer to look at.

Juttle tutorial

---

lib/compiler/ast-visitor.js
lib/compiler/build.js
lib/compiler/graph-compiler.js
lib/compiler/semantic.js
lib/parser/parser.pegjs
test/runtime/specs/juttle-spec/statements/expression-statement.spec.md
test/runtime/specs/juttle-spec/user-defined-reducers.spec.md

Expression statements replace more limited assignment statements.
Part of work on #426.

Support expression statements

---

mkdocs.yml

From: http://www.mkdocs.org/user-guide/configuration/#google_analytics
@demmer @dmehra

Add google analytics tracking

---

lib/runtime/procs/join.js

While reading through `join` code, I annotated the code with a few extra comments and did minor simplifications around conditions.
Putting them up to see if they might be useful to future readers.

Add comments & simplify conditions join

---

docs/examples/modules/array_concat.juttle
docs/examples/modules/array_join.juttle
docs/examples/modules/array_last_index_of.juttle
docs/examples/modules/array_pop.juttle
docs/examples/modules/array_push.juttle
docs/examples/modules/array_reverse.juttle
docs/examples/modules/array_shift.juttle
docs/examples/modules/array_slice.juttle
docs/examples/modules/array_sort.juttle
docs/examples/modules/array_splice.juttle
docs/examples/modules/array_to_string.juttle
docs/examples/modules/array_unshift.juttle
docs/modules/array.md

@dmehra @dmajda @bkutil 
Most of https://github.com/juttle/juttle/issues/58.

doc: array methods

---

lib/runtime/procs/read.js
test/adapters/file/read.spec.js
test/runtime/specs/juttle-test-utils.js

@demmer this is what we were discussing this am.

Handle non juttle errors in read adapter.

---

docs/examples/modules/object_to_string.juttle
docs/examples/modules/object_values.juttle
docs/examples/modules/string_char_at.juttle
docs/examples/modules/string_char_code_at.juttle
docs/examples/modules/string_from_char_code.juttle
docs/examples/modules/string_match.juttle
docs/examples/modules/string_trim.juttle
docs/modules/object.md
docs/modules/string.md

finishes https://github.com/juttle/juttle/issues/58
@dmehra @dmajda @bkutil

Document string and object functions

---

docs/concepts/programming_constructs.md
docs/reducers/mad.md
mkdocs.yml

Will merge and republish the docs.

Fixing docs links
